# -*- coding: utf-8 -*-
"""
vn_symbols_data.py — Danh sach TINH ~1398 ma co phieu HOSE/HNX/UPCOM.

Nguon: SSI iBoard (iboard-query.ssi.com.vn), chi giu co phieu thuong
(stockType="s", ma 3 ky tu chu). Dung lam fallback khi API live bi 403
tren Streamlit Cloud, de dropdown luon du ma thay vi roi ve ~35 ma.

Cap nhat: 2026-07-20. Moi phan tu: (symbol, organ_name, exchange).
"""

VN_SYMBOLS = [
    ("ADC", "Cổ phiếu Công ty Cổ phần Mĩ thuật và Truyền thông", "HNX"),
    ("ALT", "Cổ phiếu CTCP Văn hóa Tân Bình", "HNX"),
    ("AMC", "Cổ phiếu Công ty cổ phần Khoáng sản Á Châu", "HNX"),
    ("AME", "Công ty cổ phần Alphanam E&C", "HNX"),
    ("AMV", "Cổ phiếu CTCP SXKD Dược và trang thiết bị Việt Mỹ", "HNX"),
    ("API", "Cổ phiếu CTCP Đầu tư  Châu á - Thái Bình Dương", "HNX"),
    ("APS", "Cổ phiếu CTCP Chứng khoán Châu á - Thái Bình Dương", "HNX"),
    ("ARM", "ARM - CTCP Xuất nhập khẩu Hàng không", "HNX"),
    ("ATS", "Công ty Cổ phần Tập đoàn đầu tư ATS", "HNX"),
    ("BAB", "Ngân hàng Thương mại Cổ phần Bắc Á", "HNX"),
    ("BAX", "CTCP Thong Nhat", "HNX"),
    ("BBS", "Công ty cổ phần Vicem Bao bì Bút Sơn", "HNX"),
    ("BCC", "Cổ phiếu CTCP Xi măng Bỉm Sơn", "HNX"),
    ("BCF", "CTCP Thuc Pham Bich Chi", "HNX"),
    ("BED", "Cổ phiếu CTCP Sách và Thiết bị trường học đà Nẵng", "HNX"),
    ("BKC", "Cổ phiếu CTCP Khoáng sản Bắc Kạn", "HNX"),
    ("BNA", "Công ty cổ phần Tập đoàn Đầu tư Bảo Ngọc", "HNX"),
    ("BPC", "Công ty cổ phần Vicem Bao bì Bỉm Sơn", "HNX"),
    ("BTS", "Công ty cổ phần Xi măng Vicem Bút Sơn", "HNX"),
    ("BTW", "Cổ phiếu CTCP Cấp nước Bến Thành", "HNX"),
    ("BVS", "Chứng khoán CTCP chứng khoán Bảo Việt", "HNX"),
    ("BXH", "Công ty cổ phần Vicem Bao bì Hải Phòng", "HNX"),
    ("CAG", "CTCP Cảng An Giang", "HNX"),
    ("CAN", "Cổ phiếu CTCP Đồ hộp Hạ Long", "HNX"),
    ("CAP", "Cổ phiếu CTCP Lâm nông sản thực phẩm Yên Bái", "HNX"),
    ("CAR", "CTCP Tap doan Giao duc Tri Viet", "HNX"),
    ("CCR", "CTCP Cang Cam Ranh", "HNX"),
    ("CDN", "CTCP Cang Da Nang", "HNX"),
    ("CEO", "Công ty cổ phần Tập đoàn C.E.O", "HNX"),
    ("CET", "Công ty Cổ phần HTC Holding", "HNX"),
    ("CIA", "CTCP Dich vu San bay Quoc te Cam Ranh", "HNX"),
    ("CJC", "Cổ phiếu CTCP Cơ điện Miền Trung", "HNX"),
    ("CKV", "Công ty cổ phần Cokyvina", "HNX"),
    ("CLH", "CTCP Xi mang La Hien VVMI", "HNX"),
    ("CLM", "Công ty Cổ phần Xuất nhập khẩu Than - Vinacomin", "HNX"),
    ("CMC", "Cổ phiếu CTCP đầu tư CMC", "HNX"),
    ("CMS", "Công ty Cổ phần Tập đoàn CMH Việt Nam", "HNX"),
    ("CPC", "Cổ phiếu CTCP Thuốc sát trùng Cần Thơ", "HNX"),
    ("CSC", "Công ty Cổ phần Tập đoàn COTANA", "HNX"),
    ("CST", "CTCP Than Cao Sơn - TKV", "HNX"),
    ("CTB", "CTCP Che tao Bom Hai Duong", "HNX"),
    ("CTP", "Công ty cổ phần Tập đoàn CTP Group", "HNX"),
    ("CTT", "Công ty cổ phần chế tạo máy - Vinacomin", "HNX"),
    ("DAD", "Cổ phiếu CTCP Đầu tư và Phát triển Giáo dục Đà Nẵng", "HNX"),
    ("DAE", "Cổ phiếu CTCP Sách giáo dục tại Tp Đà Nẵng", "HNX"),
    ("DHP", "Cổ phiếu Công ty cổ phần điện cơ Hải Phòng", "HNX"),
    ("DHT", "Cổ phiếu CTCP Dược phẩm Hà Tây", "HNX"),
    ("DIH", "Cổ phiếu CTCP Đầu tư Phát triển Xây dựng Hội An", "HNX"),
    ("DNC", "cổ phiếu CTCP Điện nước lắp máy Hải Phòng", "HNX"),
    ("DNP", "Công ty Cổ phần DNP Holding", "HNX"),
    ("DST", "CTCP Dau Tu Sao Thang Long", "HNX"),
    ("DTD", "CTCP Đầu tư Phát triển Thành Đạt", "HNX"),
    ("DTG", "DTG- CTCP Duoc pham tipharco", "HNX"),
    ("DTK", "CTCP - Tong cong ty Dien luc TKV", "HNX"),
    ("DVM", "CTCP Dược Liệu Việt Nam", "HNX"),
    ("DXP", "Công ty Cổ phần Cảng Đoạn Xá", "HNX"),
    ("EBS", "Cổ phiếu CTCP Sách giáo dục tại Tp Hà Nội", "HNX"),
    ("ECI", "Công ty Cổ phần Tập đoàn ECI", "HNX"),
    ("EID", "Cổ phiếu CTCP Đầu tư và Phát triển Giáo dục Hà Nội", "HNX"),
    ("EVS", "Công ty cổ phần chứng khoán Everest", "HNX"),
    ("FID", "CTCP Dau tu va Phat trien Doanh nghiep Viet Nam", "HNX"),
    ("GDW", "Cổ phiếu CTCP Cấp nước Gia Định", "HNX"),
    ("GIC", "Công ty Cổ phần VSC Green Logistics", "HNX"),
    ("GKM", "Công ty Cổ phần GKM Holdings", "HNX"),
    ("GLT", "Cổ phiếu CTCP Kỹ thuật Điện Toàn Cầu", "HNX"),
    ("GMA", "Công ty Cổ phần G-Automobile", "HNX"),
    ("GMX", "Cổ phiếu Công ty Cổ phần Gạch ngói Gốm Xây dựng Mỹ Xuân", "HNX"),
    ("HAD", "Cổ phiếu CTCP Bia Hà Nội - Hải Dương", "HNX"),
    ("HAT", "Cổ phiếu CTCP Thương mại Bia Hà Nội", "HNX"),
    ("HBS", "HBS - CTCP Chứng khoán Hòa bình", "HNX"),
    ("HCC", "Công ty cổ phần Bê tông Hòa Cầm - ITEMEX", "HNX"),
    ("HCT", "Cổ phiếu  CTCP Thương mại - Dịch vụ - Vận tải Xi Măng Hải Phòng.", "HNX"),
    ("HDA", "HDA - CTCP Hãng sơn Đông Á", "HNX"),
    ("HEV", "Công Ty cổ phần sách đại học - dạy nghề", "HNX"),
    ("HGM", "Cổ phiếu CTCP Cơ khí và Khoáng sản Hà Giang", "HNX"),
    ("HHC", "Cổ phiếu CTCP Bánh kẹo Hải Hà", "HNX"),
    ("HJS", "Cổ phiếu CTCP Thuỷ điện Nậm Mu", "HNX"),
    ("HKT", "Công ty cổ phần QP Holdings", "HNX"),
    ("HLC", "Công ty cổ phần Than Hà Lầm - Vinacomin", "HNX"),
    ("HLD", "Công ty cổ phần đầu tư và Phát triển Bất Động sản HUDLAND", "HNX"),
    ("HMH", "HMH - CTCP Hải Minh", "HNX"),
    ("HMR", "Công ty cổ phần Đá Hoàng Mai", "HNX"),
    ("HOM", "Công ty Cổ phần Xi măng Vicem Hoàng Mai", "HNX"),
    ("HTC", "Cổ phiếu CTCP Thương mại Hóc Môn", "HNX"),
    ("HUT", "Cổ phiếu CTCP Tasco", "HNX"),
    ("HVT", "Cổ phiếu Công ty Cổ phần Hóa chất Việt Trì", "HNX"),
    ("ICG", "Cổ phiếu CTCP Xây dựng Sông Hồng", "HNX"),
    ("IDC", "Tổng Công ty IDICO - CTCP", "HNX"),
    ("IDJ", "Công ty Cổ phần Đầu tư IDJ Việt Nam", "HNX"),
    ("IDV", "IDV - Công ty Cổ phần Phát triển hạ tầng Vĩnh Phúc", "HNX"),
    ("INC", "Cổ phiếu CTCP Tư vấn đầu tư IDICO", "HNX"),
    ("INN", "Cổ phiếu CTCP Bao bì và In Nông nghiệp", "HNX"),
    ("IPA", "CTCP Tap doan dau tu I.P.A", "HNX"),
    ("ITQ", "Cổ phiếu Công ty cổ phần Tập đoàn Thiên Quang", "HNX"),
    ("IVS", "Công ty Cổ phần Chứng khoán Guotai Haitong (Việt Nam)", "HNX"),
    ("KDM", "Công ty cổ phần Tập đoàn GCL", "HNX"),
    ("KHS", "Công ty cổ phần Kiên Hùng", "HNX"),
    ("KKC", "Công ty cổ phần Tập đoàn Thành Thái", "HNX"),
    ("KMT", "Công ty Cổ phần Kim Khí Miền Trung", "HNX"),
    ("KSD", "Công ty Cổ phần Đầu tư DNA", "HNX"),
    ("KSF", "Công ty Cổ phần Tập đoàn Sunshine", "HNX"),
    ("KST", "Công ty Cổ phần KASATI", "HNX"),
    ("KSV", "Tong Cong ty Khoang san TKV-CTCP", "HNX"),
    ("KTS", "Cổ phiếu CTCP Đường Kon Tum", "HNX"),
    ("LAS", "Cổ phiếu Công ty Cổ phần Supe Phốt phát và Hóa chất Lâm Thao", "HNX"),
    ("LBE", "Công ty cổ phần Thương mại và Dịch vụ LVA", "HNX"),
    ("LCD", "Công ty cổ phần Lắp máy - Thí nghiệm Cơ Điện", "HNX"),
    ("LDP", "Cổ phiếu CTCP Dược Lâm Đồng - Ladophar", "HNX"),
    ("LHC", "Cổ phiếu CTCP Đầu tư và xây dựng thủy lợi Lâm Đồng", "HNX"),
    ("LIG", "Cổ phiếu CTCP LICOGI13", "HNX"),
    ("MAC", "Công ty Cổ phần Tập đoàn Macstar", "HNX"),
    ("MAS", "Cổ phiếu CTCP Dịch vụ Hàng không Sân bay Đà Nẵng", "HNX"),
    ("MBG", "Công ty cổ phần Tập đoàn MBG", "HNX"),
    ("MBS", "CTCP Chung khoan MB", "HNX"),
    ("MCC", "Cổ phiếu CTCP Gạch ngói cao cấp", "HNX"),
    ("MCF", "Cổ phếu CTCP Xây lắp Cơ khí & Lương thực Thực phẩm", "HNX"),
    ("MCO", "Công ty cổ phần Đầu tư và Xây dựng BDC Việt Nam", "HNX"),
    ("MDC", "Công ty cổ phần Than Mông Dương Vinacomin", "HNX"),
    ("MED", "CTCP Dược Trung Ương Mediplantex", "HNX"),
    ("MEL", "CTCP Thép Mê Lin", "HNX"),
    ("MIC", "Cổ phiếu CTCP Kỹ nghệ Khoáng sản Quảng Nam", "HNX"),
    ("MKV", "Cổ phiếu CTCP dược thú y Cai Lậy", "HNX"),
    ("MST", "Công ty cổ phần Đầu tư MST", "HNX"),
    ("MVB", "TCT Cong nghiep mo Viet Bac TKV", "HNX"),
    ("NAG", "Công ty cổ phần Tập đoàn Nagakawa Việt Nam", "HNX"),
    ("NAP", "CTCP Cang Nghe Tinh", "HNX"),
    ("NBC", "Công ty cổ phần Than Núi Béo - Vinacomin", "HNX"),
    ("NBP", "Cổ phiếu CTCP Nhiệt điện Ninh Bình", "HNX"),
    ("NBW", "Cổ phiếu CTCP Cấp nước Nhà Bè", "HNX"),
    ("NDN", "Cổ phiếu công ty Cổ phần Đầu tư Phát triển Nhà Đà Nẵng", "HNX"),
    ("NDX", "Cổ phiếu CTCP xây lắp phát triển nhà Đà Nẵng", "HNX"),
    ("NET", "Cổ phiếu Công ty Cổ phần Bột giặt NET", "HNX"),
    ("NFC", "NFC-CTCP Phân lân Ninh Bình", "HNX"),
    ("NHC", "Cổ  Phiếu CTCP Gạch ngói Nhị Hiệp", "HNX"),
    ("NRC", "Công ty cổ phần Tập đoàn Danh Khôi", "HNX"),
    ("NSH", "Công ty cổ phần Tập đoàn Nhôm Sông Hồng Shalumi", "HNX"),
    ("NST", "Cổ phiếu CTCP Ngân Sơn", "HNX"),
    ("NTH", "CTCP Thủy điện Nước Trong", "HNX"),
    ("NTP", "Cổ phiếu CTCP Nhựa thiếu niên -Tiền Phong", "HNX"),
    ("NVB", "Ngân hàng Thương mại cổ phần Quốc Dân", "HNX"),
    ("OCH", "Công ty cổ phần One Capital Hospitality", "HNX"),
    ("ONE", "Công ty cổ phần Công nghệ ONE", "HNX"),
    ("PBP", "CTCP Bao bì Dầu khí Việt Nam", "HNX"),
    ("PCE", "CTCP Phan bon va Hoa chat Dau khi Mien Trung", "HNX"),
    ("PCH", "Công Ty Cổ phần Picomat Holding", "HNX"),
    ("PCT", "Công ty cổ phần Vận tải biển Global Pacific", "HNX"),
    ("PDB", "Công ty Cổ phần Tập đoàn Đầu tư Din Capital", "HNX"),
    ("PEN", "CTCP Xây lắp III Petrolimex", "HNX"),
    ("PGN", "CTCP Phu Gia Nhua", "HNX"),
    ("PGS", "Công ty cổ phần Kinh doanh Khí miền Nam", "HNX"),
    ("PGT", "Công ty cổ phần PGT HOLDINGS", "HNX"),
    ("PHN", "Công ty cổ phần Pin Hà Nội", "HNX"),
    ("PIA", "CTCP Tin hoc Vien thong Petrolimex", "HNX"),
    ("PIC", "CTCP Dau tu Dien luc 3", "HNX"),
    ("PJC", "Cổ phiếu CTCP Thương mại và Vận tải Petrolimex Hà Nội (Petajico HaNoi)", "HNX"),
    ("PLC", "Cổ phiếu Tổng Công ty Hóa dầu Petrolimex - CTCP", "HNX"),
    ("PMB", "CTCP Phan bon va Hoa chat Dau khi Mien Bac", "HNX"),
    ("PMC", "Cổ phiếu CTCP Dược phẩm dược liệu Pharmedic", "HNX"),
    ("PMP", "CTCP Bao bi Dam Phu My", "HNX"),
    ("PMS", "Cổ phiếu công ty cổ phần Cơ khí Xăng Dầu", "HNX"),
    ("POT", "Cổ phiếu CTCP Thiết bị Bưu điện", "HNX"),
    ("PPE", "Công ty cổ phần Tư vấn Đầu Tư PP Enterprise", "HNX"),
    ("PPP", "Cổ phiếu CTCP Dược phẩm Phong Phú", "HNX"),
    ("PPS", "PPS - Công ty Cổ phần Dịch vụ Kỹ thuật Điện lực Dầu khí Việt Nam", "HNX"),
    ("PPT", "CTCP Petrotimes", "HNX"),
    ("PPY", "CTCP Xang Dau Dau khi Phu Yen", "HNX"),
    ("PRC", "Công ty cổ phần Logistics Portserco", "HNX"),
    ("PRE", "Công ty cổ phần Tái bảo hiểm Hà Nội", "HNX"),
    ("PSC", "Cổ phiếu CTCP Vận tải và Dịch vụ Petrolimex Sài Gòn", "HNX"),
    ("PSD", "Cổ phiếu Công ty cổ phần Dịch vụ Phân phối Tổng hợp Dầu khí", "HNX"),
    ("PSE", "CTCP Phân bón và Hóa chất Dầu khí Đông Nam Bộ", "HNX"),
    ("PSI", "PSI - Cổ phiếu Công ty Cổ phần Chứng khoán Dầu Khí", "HNX"),
    ("PSW", "PSW - CTCP Phan Bon va Hoa Chat Dau khi Tay Nam Bo", "HNX"),
    ("PTD", "PTD - CTCP Thiết kế Xây dựng Thương mại Phúc Thịnh", "HNX"),
    ("PTI", "PTI - Tổng CTCP Bảo hiểm Bưu điện", "HNX"),
    ("PTS", "Cổ phiếu CTCP Vận tải và Dịch vụ Petrolimex Hải Phòng", "HNX"),
    ("PTX", "CTCP Van tai va Dich vu Petrolimex Nghe Tinh", "HNX"),
    ("PVB", "Cổ phiếu CTCP Bọc ống dầu khí Việt Nam", "HNX"),
    ("PVC", "Cổ phiếu Tổng Công ty Hóa chất và Dịch vụ Dầu khí - CTCP (PVChem)", "HNX"),
    ("PVG", "Công ty cổ phần Kinh doanh LPG Việt Nam", "HNX"),
    ("PVI", "Công ty cổ phần PVI", "HNX"),
    ("PVS", "Cổ phiếu Tổng CTCP Dịch Vụ Kỹ Thuật Dầu Khí Việt Nam", "HNX"),
    ("QHD", "Cổ phiếu công ty cổ phần Que hàn điện Việt Đức", "HNX"),
    ("QST", "Cổ phiếu CTCP Sách và thiết bị trường học Quảng Ninh", "HNX"),
    ("QTC", "Cổ phiếu CTCP Công trình GTVT Quảng Nam", "HNX"),
    ("RCL", "Cổ phiếu CTCP Địa ốc Chợ Lớn", "HNX"),
    ("SAF", "Cổ phiếu CTCP Lương thực Thực phẩm Safoco", "HNX"),
    ("SCG", "Công ty cổ phần Tập đoàn Xây dựng SCG", "HNX"),
    ("SCI", "Công ty cổ phần SIC E&C", "HNX"),
    ("SDC", "Cổ phiếu Công ty Cổ phần Tư vấn Sông Đà", "HNX"),
    ("SDG", "Cổ phiếu Công ty cổ phần Sadico Cần Thơ", "HNX"),
    ("SDN", "Cổ phiếu CTCP Sơn Đồng Nai", "HNX"),
    ("SDU", "Công ty cổ phần Đầu tư xây dựng và phát triển đô thị Sông Đà", "HNX"),
    ("SEB", "Cổ phiếu Công ty CP Đầu tư và Phát triển Điện Miền Trung", "HNX"),
    ("SED", "Cổ phiếu CTCP Đầu tư và Phát triển Giáo dục Phương Nam", "HNX"),
    ("SFN", "Cổ phiếu CTCP Dệt lưới Sài Gòn", "HNX"),
    ("SGC", "cổ phiếu CTCP Xuất nhập khẩu Sa Giang", "HNX"),
    ("SGD", "Cổ phiếu CTCP Sách giáo dục tại Tp.HCM", "HNX"),
    ("SGH", "Cổ phiếu CTCP Khách sạn Sài Gòn", "HNX"),
    ("SHE", "CTCP Phat trien nang luong Son Ha", "HNX"),
    ("SHN", "Cổ phiếu CTCP Đầu tư Tổng hợp Hà Nội", "HNX"),
    ("SHS", "Cổ phiếu CTCP Chứng khoán Sài Gòn - Hà Nội", "HNX"),
    ("SJE", "Cổ phiếu CTCP Sông Đà 11", "HNX"),
    ("SLS", "SLS - Công ty cổ phần Mía đường Sơn La", "HNX"),
    ("SMN", "SMN - CTCP Sach va Thiet bi Giao duc Mien nam", "HNX"),
    ("SMT", "Công ty Cổ phần Sametel", "HNX"),
    ("SPC", "SPC - CTCP Bảo vệ Thực vật Sài Gòn", "HNX"),
    ("SRA", "Cổ phiếu CTCP SARA Việt Nam", "HNX"),
    ("SSM", "Cổ phiếu CTCP Chế tạo kết cấu thép VNECO.SSM", "HNX"),
    ("STC", "Cổ phiếu CTCP Sách và Thiết bị Trường học tại Tp, HCM", "HNX"),
    ("STP", "Cổ phiếu CTCP Công nghiệp Thương mại Sông Đà", "HNX"),
    ("SVN", "Công ty cổ phần Tập đoàn Vexilla Việt Nam", "HNX"),
    ("SZB", "CTCP Sonadezi Long Binh", "HNX"),
    ("TDT", "CTCP Dau tu va phat trien TDT", "HNX"),
    ("TET", "Cổ phiếu CTCP Vải sợi may mặc Miền Bắc", "HNX"),
    ("TFC", "CTCP Trang", "HNX"),
    ("THB", "Công ty cổ phần Bia Hà Nội - Thanh Hóa", "HNX"),
    ("THD", "CTCP Thaiholdings", "HNX"),
    ("THS", "CTCP Thanh Hoa - Sông Đà", "HNX"),
    ("THT", "Công ty cổ phần Than Hà Tu - Vinacomin", "HNX"),
    ("TIG", "Cổ phiếu CTCP Tập đoàn Đầu tư Thăng Long", "HNX"),
    ("TJC", "Cổ phiếu CTCP Dịch vụ Vận tải và Thương mại", "HNX"),
    ("TKU", "Cổ phiếu CTCP Công nghiệp Tung Kuang", "HNX"),
    ("TMB", "CTCP Kinh doanh than Mien Bac - Vinacomin", "HNX"),
    ("TMC", "Cổ phiếu CTCP Thương mại và Xuất nhập khẩu Thủ Đức", "HNX"),
    ("TMX", "Công ty cổ phần VICEM Thương mại Xi măng", "HNX"),
    ("TNG", "Cổ phiếu CTCP Đầu tư và Thương mại TNG", "HNX"),
    ("TOT", "Công ty cổ phần Transimex Logistics", "HNX"),
    ("TPP", "Công ty cổ phần Tân Phú Việt Nam", "HNX"),
    ("TSB", "Cổ phiếu CTCP Ắc qui Tia Sáng", "HNX"),
    ("TTC", "Cổ phiếu CTCP Gạch men Thanh Thanh", "HNX"),
    ("TTH", "CTCP Thuong mai va Dich vu Tien Thanh", "HNX"),
    ("TTL", "CTCP Tong cong ty Thang Long", "HNX"),
    ("TTT", "CTCP Du lich-Thuong mai Tay Ninh", "HNX"),
    ("TVC", "Công ty cổ phần Tập đoàn Quản lý tài sản Trí Việt", "HNX"),
    ("TVD", "Công ty cổ phần Than Vàng Danh - Vinacomin", "HNX"),
    ("TXM", "Cổ phiếu CTCP Vicem Thạch cao Xi măng", "HNX"),
    ("UNI", "Công ty cổ phần Đầu tư và Phát triển Sao Mai Việt", "HNX"),
    ("VBC", "Cổ phiếu CTCP Nhựa - Bao bì Vinh", "HNX"),
    ("VCC", "Cổ phiếu Công ty cổ phần Vinaconex 25", "HNX"),
    ("VCM", "Công ty Cổ phần BV Life", "HNX"),
    ("VCS", "Cổ phiếu CTCP VICOSTONE", "HNX"),
    ("VDL", "Cổ phiếu CTCP Thực phẩm Lâm Đồng", "HNX"),
    ("VFS", "CTCP Chung khoan Nhat Viet", "HNX"),
    ("VGP", "Cổ phiếu CTCP Cảng Rau Quả", "HNX"),
    ("VGS", "Cổ phiếu CTCP ống thép Việt Đức VG PIPE", "HNX"),
    ("VHE", "CTCP Duoc lieu va Thuc pham Viet nam", "HNX"),
    ("VHL", "Cổ phiếu Cty cổ phần Viglacera Hạ Long", "HNX"),
    ("VIF", "TCT Lam nghiep Viet Nam - CTCP", "HNX"),
    ("VIG", "Công ty cổ phần Chứng khoán Đầu tư Tài chính Việt Nam", "HNX"),
    ("VIT", "Cổ phiếu CTCP Viglacera Tiên Sơn", "HNX"),
    ("VLA", "VLA - CTCP Đầu tư và Phát triển Công nghệ Văn Lang", "HNX"),
    ("VMC", "Cổ phiếu Công ty cổ phần VIMECO", "HNX"),
    ("VMS", "CTCP Phat trien Hang hai", "HNX"),
    ("VNC", "Công ty cổ phần Tập đoàn Vinacontrol", "HNX"),
    ("VNF", "Công ty cổ phần Vinafreight", "HNX"),
    ("VNR", "Cổ phiếu Tổng CTCP Tái Bảo hiểm Quốc gia Việt Nam", "HNX"),
    ("VNT", "Cổ phiếu Công ty cổ phần Giao nhận vận tải Ngoại thương", "HNX"),
    ("VSA", "CTCP Dai ly Hang hai Viet Nam", "HNX"),
    ("VSM", "CTCP Container Mien Trung", "HNX"),
    ("VTC", "cổ phần Công ty cổ phần Viễn thông VTC", "HNX"),
    ("VTH", "VTH - CTCP Day cap dien Viet Thai", "HNX"),
    ("VTJ", "CTCP Thương mại và Đầu tư Vinataba", "HNX"),
    ("VTV", "Công ty cổ phần Năng lượng và Môi trường VICEM", "HNX"),
    ("VTZ", "CTCP San xuat va Thuong mai Nhua Viet Thanh", "HNX"),
    ("WCS", "WCS - Công ty cổ phần Bến Xe Miền Tây", "HNX"),
    ("WSS", "Cổ phiếu CTCP Chứng khoán Phố Wall", "HNX"),
    ("AAA", "Công ty Cổ phần Nhựa An Phát Xanh", "HOSE"),
    ("AAM", "Công ty Cổ phần Thủy sản Mekong", "HOSE"),
    ("AAN", "Công ty Cổ phần Lương thực A An", "HOSE"),
    ("AAT", "Công ty Cổ phần Tập đoàn Tiên Sơn Thanh Hóa", "HOSE"),
    ("ABR", "Công ty Cổ phần Đầu tư Nhãn hiệu Việt", "HOSE"),
    ("ABS", "Công ty Cổ phần Dịch vụ Nông nghiệp Bình Thuận", "HOSE"),
    ("ABT", "Công ty Cổ phần Xuất nhập khẩu Thủy sản Bến Tre", "HOSE"),
    ("ACB", "Ngân hàng Thương mại Cổ phần Á Châu", "HOSE"),
    ("ACC", "Công ty Cổ phần Đầu tư và Xây dựng Bình Dương ACC", "HOSE"),
    ("ACG", "Công ty Cổ phần Gỗ An Cường", "HOSE"),
    ("ACL", "Công ty Cổ phần Xuất Nhập Khẩu Thủy sản Cửu Long An Giang", "HOSE"),
    ("ADG", "Công ty Cổ phần Clever Group", "HOSE"),
    ("ADP", "Công ty Cổ phần Sơn Á Đông", "HOSE"),
    ("ADS", "Công ty Cổ phần Damsan", "HOSE"),
    ("AFX", "CTCP Xuất nhập khẩu Nông sản Thực phẩm An Giang", "HOSE"),
    ("AGG", "Công ty Cổ phần Đầu tư và Phát triển Bất động sản An Gia", "HOSE"),
    ("AGR", "Công ty Cổ phần Chứng khoán Agribank", "HOSE"),
    ("ANT", "Công ty cổ phần Rau quả thực phẩm An Giang", "HOSE"),
    ("ANV", "Công ty Cổ phần Nam Việt", "HOSE"),
    ("APG", "Công ty Cổ phần Chứng khoán APG", "HOSE"),
    ("APH", "Công ty Cổ phần Tập đoàn An Phát Holdings", "HOSE"),
    ("ASG", "Công ty Cổ phần Tập đoàn ASG", "HOSE"),
    ("ASM", "Công ty Cổ phần Tập đoàn Sao Mai", "HOSE"),
    ("ASP", "Công ty Cổ phần Tập đoàn Dầu khí An Pha", "HOSE"),
    ("AST", "Công ty Cổ phần Dịch vụ Hàng không Taseco", "HOSE"),
    ("BAF", "Công ty Cổ phần Nông nghiệp BAF Việt Nam", "HOSE"),
    ("BCE", "Công ty Cổ phần Xây dựng và Giao thông Bình Dương", "HOSE"),
    ("BCM", "Tập đoàn Đầu tư và Phát triển Công nghiệp Becamex - CTCP", "HOSE"),
    ("BFC", "Công ty Cổ phần Phân bón Bình Điền", "HOSE"),
    ("BHN", "Tổng Công ty Cổ phần Bia – Rượu – Nước giải khát Hà Nội", "HOSE"),
    ("BIC", "Tổng Công ty Bảo hiểm Ngân hàng Đầu tư và Phát triển Việt Nam", "HOSE"),
    ("BID", "Ngân hàng Thương mại Cổ phần Đầu tư và Phát triển Việt Nam", "HOSE"),
    ("BKG", "Công ty Cổ phần Đầu tư BKG Việt Nam", "HOSE"),
    ("BMC", "Công ty Cổ phần Khoáng sản Bình Định", "HOSE"),
    ("BMI", "Tổng Công ty Cổ phần Bảo Minh", "HOSE"),
    ("BMP", "Công ty Cổ phần Nhựa Bình Minh", "HOSE"),
    ("BRC", "Công ty Cổ phần Cao su Bến Thành", "HOSE"),
    ("BSI", "Công ty Cổ phần Chứng khoán BIDV", "HOSE"),
    ("BSR", "CÔNG TY CỔ PHẦN – TỔNG CÔNG TY LỌC HÓA DẦU VIỆT NAM", "HOSE"),
    ("BTP", "Công ty Cổ phần Nhiệt điện Bà Rịa", "HOSE"),
    ("BTT", "Công ty Cổ phần Thương mại – Dịch vụ Bến Thành", "HOSE"),
    ("BVH", "Tập đoàn Bảo Việt", "HOSE"),
    ("BWE", "Công ty Cổ phần - Tổng Công ty Nước – Môi trường Bình Dương", "HOSE"),
    ("CCC", "Công ty Cổ phần Xây dựng CDC", "HOSE"),
    ("CCI", "Công ty Cổ phần Đầu tư Phát triển Công nghiệp Thương mại Củ Chi", "HOSE"),
    ("CCL", "Công ty Cổ phần Đầu tư và Phát triển Đô thị Dầu khí Cửu Long", "HOSE"),
    ("CDC", "Công ty Cổ phần Chương Dương", "HOSE"),
    ("CHP", "Công ty Cổ phần Thủy điện Miền Trung", "HOSE"),
    ("CIG", "Công ty Cổ phần COMA18", "HOSE"),
    ("CII", "Công ty Cổ phần Đầu tư Hạ tầng Kỹ thuật TP.HCM", "HOSE"),
    ("CKG", "Công ty Cổ phần Tập đoàn CIC", "HOSE"),
    ("CLC", "Công ty Cổ phần Cát Lợi", "HOSE"),
    ("CLL", "Công ty Cổ phần Cảng Cát Lái", "HOSE"),
    ("CLW", "Công ty Cổ phần Cấp nước Chợ Lớn", "HOSE"),
    ("CMG", "Công ty Cổ phần Tập đoàn Công nghệ CMC", "HOSE"),
    ("CMV", "Công ty Cổ phần Thương nghiệp Cà Mau", "HOSE"),
    ("CMX", "Công ty Cổ phần Camimex Group", "HOSE"),
    ("CNG", "Công ty Cổ phần CNG Việt Nam", "HOSE"),
    ("COM", "Công ty Cổ phần Vật tư - Xăng dầu", "HOSE"),
    ("CRC", "Công ty Cổ phần Create Capital Việt Nam", "HOSE"),
    ("CRE", "Công ty Cổ phần Bất động sản Thế Kỷ", "HOSE"),
    ("CRV", "Công ty Cổ phần Tập đoàn Bất động sản CRV", "HOSE"),
    ("CSM", "Công ty Cổ phần Công nghiệp Cao su Miền Nam", "HOSE"),
    ("CSV", "Công ty Cổ phần Hóa chất cơ bản miền Nam", "HOSE"),
    ("CTD", "Công ty Cổ phần Xây dựng COTECCONS", "HOSE"),
    ("CTF", "Công ty Cổ phần City Auto", "HOSE"),
    ("CTG", "Ngân hàng Thương mại Cổ phần Công Thương Việt Nam", "HOSE"),
    ("CTI", "Công ty Cổ phần Đầu tư Phát triển Cường Thuận IDICO", "HOSE"),
    ("CTR", "Tổng Công ty Cổ phần Công trình Viettel", "HOSE"),
    ("CTS", "Công ty Cổ phần Chứng khoán VIETINBANK", "HOSE"),
    ("CVT", "Công ty Cổ phần CMC", "HOSE"),
    ("DAH", "Công ty Cổ phần Tập đoàn Khách sạn Đông Á", "HOSE"),
    ("DAT", "Công ty Cổ phần Đầu tư Du lịch và Phát triển Thủy sản", "HOSE"),
    ("DBC", "Công ty Cổ phần Tập đoàn DABACO Việt Nam", "HOSE"),
    ("DBD", "Công ty Cổ phần Dược - Trang thiết bị Y tế Bình Định", "HOSE"),
    ("DBT", "Công ty Cổ phần Dược phẩm Bến Tre", "HOSE"),
    ("DCL", "Công ty Cổ phần Dược phẩm Cửu Long", "HOSE"),
    ("DCM", "Công ty Cổ phần - Tổng Công ty phân bón Dầu khí Cà Mau", "HOSE"),
    ("DGC", "Công ty Cổ phần Tập đoàn Hóa chất Đức Giang", "HOSE"),
    ("DGW", "Công ty Cổ phần Thế Giới Số", "HOSE"),
    ("DHA", "Công ty Cổ phần Hóa An", "HOSE"),
    ("DHC", "Công ty Cổ phần Đông Hải Bến Tre", "HOSE"),
    ("DHG", "Công ty Cổ phần Dược Hậu Giang", "HOSE"),
    ("DHM", "Công ty Cổ phần Đầu tư và Thương mại DHM", "HOSE"),
    ("DIG", "Tổng Công ty Cổ phần Đầu tư Phát triển Xây dựng", "HOSE"),
    ("DLG", "Công ty Cổ phần Tập đoàn Đức Long Gia Lai", "HOSE"),
    ("DMC", "Công ty Cổ phần Xuất nhập khẩu Y tế DOMESCO", "HOSE"),
    ("DPG", "Công ty Cổ phần Tập đoàn Đạt Phương", "HOSE"),
    ("DPM", "Tổng Công ty Phân bón và Hóa chất Dầu khí - Công ty Cổ phần", "HOSE"),
    ("DPR", "Công ty Cổ phần Cao su Đồng Phú", "HOSE"),
    ("DQC", "Công ty Cổ phần Tập đoàn Điện Quang", "HOSE"),
    ("DRC", "Công ty Cổ phần Cao su Đà Nẵng", "HOSE"),
    ("DRH", "Công ty Cổ phần DRH Holdings", "HOSE"),
    ("DRL", "Công ty Cổ phần Thủy điện - Điện lực 3", "HOSE"),
    ("DSC", "Công ty Cổ phần Chứng khoán DSC", "HOSE"),
    ("DSE", "Công ty Cổ phần Chứng khoán DNSE", "HOSE"),
    ("DSN", "Công ty Cổ phần Công viên nước Đầm Sen", "HOSE"),
    ("DTA", "Công ty Cổ phần Đệ Tam", "HOSE"),
    ("DTL", "Công ty Cổ phần Đại Thiên Lộc", "HOSE"),
    ("DTT", "Công ty Cổ phần Kỹ nghệ Đô Thành", "HOSE"),
    ("DVP", "Công ty Cổ phần Đầu tư và Phát triển Cảng Đình Vũ", "HOSE"),
    ("DXG", "Công ty Cổ phần Bluemarq Group", "HOSE"),
    ("DXS", "Công ty Cổ phần Dịch vụ Bất động sản Đất Xanh", "HOSE"),
    ("DXV", "Công ty Cổ phần Vicem Vật liệu Xây dựng Đà Nẵng", "HOSE"),
    ("EIB", "Ngân hàng Thương mại Cổ phần Xuất Nhập khẩu Việt Nam", "HOSE"),
    ("ELC", "Công ty Cổ phần Công nghệ - Viễn thông ELCOM", "HOSE"),
    ("EVE", "Công ty Cổ phần Everpia", "HOSE"),
    ("EVF", "CÔNG TY TÀI CHÍNH TỔNG HỢP CỔ PHẦN ĐIỆN LỰC", "HOSE"),
    ("EVG", "Công ty Cổ phần Tập đoàn Everland", "HOSE"),
    ("FCM", "Công ty Cổ phần Bê tông Phan Vũ Hà Nam", "HOSE"),
    ("FCN", "Công ty Cổ phần FECON", "HOSE"),
    ("FDC", "Công ty Cổ phần Ngoại thương và Phát triển Đầu tư Thành phố Hồ Chí Minh", "HOSE"),
    ("FIR", "Công ty Cổ phần Địa ốc First Real", "HOSE"),
    ("FIT", "Công ty Cổ phần Tập đoàn F.I.T", "HOSE"),
    ("FMC", "Công ty Cổ phần Thực phẩm Sao Ta", "HOSE"),
    ("FPT", "Công ty Cổ phần FPT", "HOSE"),
    ("FRT", "Công ty Cổ phần Bán lẻ Kỹ thuật số FPT", "HOSE"),
    ("FTS", "Công ty Cổ phần Chứng khoán FPT", "HOSE"),
    ("GAS", "Tổng Công ty Khí Việt Nam - Công ty Cổ phần", "HOSE"),
    ("GDT", "Công ty Cổ phần Chế biến Gỗ Đức Thành", "HOSE"),
    ("GEE", "Công ty Cổ phần Điện lực Gelex", "HOSE"),
    ("GEG", "Công ty Cổ phần Điện Gia Lai", "HOSE"),
    ("GEL", "Công ty Cổ phần Hạ tầng GELEX", "HOSE"),
    ("GEX", "Công ty Cổ phần Tập đoàn GELEX", "HOSE"),
    ("GHC", "Công ty Cổ phần Thủy điện Gia Lai", "HOSE"),
    ("GIL", "Công ty Cổ phần Sản xuất Kinh doanh Xuất nhập khẩu Bình Thạnh", "HOSE"),
    ("GMD", "CÔNG TY CỔ PHẦN TẬP ĐOÀN GEMADEPT", "HOSE"),
    ("GMH", "Công ty Cổ phần Minh Hưng Quảng Trị", "HOSE"),
    ("GSP", "Công ty Cổ phần Vận tải Sản phẩm Khí Quốc tế", "HOSE"),
    ("GTA", "Công ty Cổ phần Chế biến Gỗ Thuận An", "HOSE"),
    ("GVR", "Tập đoàn Công nghiệp Cao su Việt Nam - Công ty Cổ phần", "HOSE"),
    ("HAG", "Công ty Cổ phần Hoàng Anh Gia Lai", "HOSE"),
    ("HAH", "Công ty Cổ phần Vận tải và Xếp dỡ Hải An", "HOSE"),
    ("HAP", "Công ty Cổ phần Tập đoàn HAPACO", "HOSE"),
    ("HAR", "Công ty Cổ phần Đầu tư Thương mại Bất động sản An Dương Thảo Điền", "HOSE"),
    ("HAS", "Công ty Cổ phần HACISCO", "HOSE"),
    ("HAX", "Công ty Cổ phần Dịch vụ Ô tô Hàng Xanh", "HOSE"),
    ("HCD", "Công ty Cổ phần Đầu tư Sản xuất và Thương mại HCD", "HOSE"),
    ("HCM", "Công ty Cổ phần Chứng khoán Thành phố Hồ Chí Minh", "HOSE"),
    ("HDB", "Ngân hàng Thương mại Cổ phần Phát triển Thành phố Hồ Chí Minh", "HOSE"),
    ("HDC", "Công ty Cổ phần Phát triển nhà Bà Rịa – Vũng Tàu", "HOSE"),
    ("HDG", "Công ty Cổ phần Tập đoàn Hà Đô", "HOSE"),
    ("HHP", "Công ty Cổ phần HHP Global", "HOSE"),
    ("HHS", "Công ty Cổ phần Đầu tư Dịch vụ Hoàng Huy", "HOSE"),
    ("HHV", "Công ty Cổ phần Đầu tư Hạ tầng Giao thông Đèo Cả", "HOSE"),
    ("HID", "Công ty Cổ phần Halcom Việt Nam", "HOSE"),
    ("HII", "Công ty Cổ phần An Tiến Industries", "HOSE"),
    ("HMC", "Công ty Cổ phần Kim khí Thành phố Hồ Chí Minh - Vnsteel", "HOSE"),
    ("HNA", "Công ty Cổ phần Thủy điện Hủa Na", "HOSE"),
    ("HPA", "Công ty Cổ phần Phát triển Nông nghiệp Hòa Phát", "HOSE"),
    ("HPG", "Công ty Cổ phần Tập đoàn Hòa Phát", "HOSE"),
    ("HPX", "Công ty Cổ phần Đầu tư Hải Phát", "HOSE"),
    ("HQC", "Công ty Cổ phần Tư vấn – Thương mại – Dịch vụ Địa ốc Hoàng Quân", "HOSE"),
    ("HRC", "Công ty Cổ phần Cao su Hòa Bình", "HOSE"),
    ("HSG", "Công ty Cổ phần Tập đoàn Hoa Sen", "HOSE"),
    ("HSL", "Công ty Cổ phần Đầu tư Phát triển Thực phẩm Hồng Hà", "HOSE"),
    ("HTG", "Tổng Công ty Cổ phần Dệt may Hòa Thọ", "HOSE"),
    ("HTI", "Công ty Cổ phần Đầu tư Phát triển Hạ tầng IDICO", "HOSE"),
    ("HTL", "Công ty Cổ phần Kỹ thuật và Ô tô Trường Long", "HOSE"),
    ("HTN", "Công ty Cổ phần Hưng Thịnh Incons", "HOSE"),
    ("HTV", "Công ty Cổ phần Logistics Vicem", "HOSE"),
    ("HUB", "Công ty Cổ phần Xây lắp Thừa Thiên Huế", "HOSE"),
    ("HVH", "Công ty Cổ phần Đầu tư và Công nghệ HVC", "HOSE"),
    ("HVN", "Tổng Công ty Hàng không Việt Nam - CTCP", "HOSE"),
    ("ICT", "Công ty Cổ phần Viễn thông - Tin học Bưu điện", "HOSE"),
    ("IDI", "Công ty Cổ phần Đầu tư và Phát triển Đa Quốc Gia I.D.I", "HOSE"),
    ("IJC", "Công ty Cổ phần Phát triển Hạ tầng Kỹ thuật", "HOSE"),
    ("ILB", "Công ty Cổ phần ICD Tân Cảng - Long Bình", "HOSE"),
    ("IMP", "Công ty Cổ phần Dược phẩm Imexpharm", "HOSE"),
    ("ITC", "Công ty Cổ phần Đầu tư - Kinh doanh Nhà", "HOSE"),
    ("ITD", "Công ty Cổ phần Công Nghệ ITD", "HOSE"),
    ("JVC", "Công ty Cổ phần Đầu tư Y tế - Dược Phẩm Việt Nam", "HOSE"),
    ("KBC", "Tổng Công ty Phát triển Đô Thị Kinh Bắc – Công ty Cổ phần", "HOSE"),
    ("KDC", "Công ty Cổ phần Tập đoàn Kido", "HOSE"),
    ("KDH", "Công ty Cổ phần Đầu tư và Kinh doanh Nhà Khang Điền", "HOSE"),
    ("KHG", "Công ty Cổ phần Tập đoàn Khải Hoàn Land", "HOSE"),
    ("KHP", "Công ty Cổ phần Điện lực Khánh Hòa", "HOSE"),
    ("KLB", "Ngân hàng Thương mại Cổ phần Kiên Long", "HOSE"),
    ("KMR", "Công ty Cổ phần MIRAE", "HOSE"),
    ("KOS", "Công ty Cổ phần KOSY", "HOSE"),
    ("KSB", "Công ty Cổ phần Khoáng sản và Xây dựng Bình Dương", "HOSE"),
    ("LAF", "Công ty Cổ phần Chế biến Hàng xuất khẩu Long An", "HOSE"),
    ("LBM", "Công ty Cổ phần Khoáng sản và Vật liệu Xây dựng Lâm Đồng", "HOSE"),
    ("LCG", "Công ty Cổ phần Lizen", "HOSE"),
    ("LDG", "Công ty Cổ phần Đầu tư LDG", "HOSE"),
    ("LGC", "Công ty Cổ phần Đầu tư Cầu Đường CII", "HOSE"),
    ("LGL", "Công ty Cổ phần Đầu tư và Phát triển Đô thị Long Giang", "HOSE"),
    ("LHG", "Công ty Cổ phần Long Hậu", "HOSE"),
    ("LIX", "Công ty Cổ phần Bột giặt LIX", "HOSE"),
    ("LPB", "Ngân hàng Thương mại Cổ phần Lộc Phát Việt Nam", "HOSE"),
    ("LSS", "Công ty Cổ phần Mía đường Lam Sơn", "HOSE"),
    ("MBB", "Ngân hàng Thương mại Cổ phần Quân Đội", "HOSE"),
    ("MCH", "Công ty cổ phần Hàng tiêu dùng Masan", "HOSE"),
    ("MCM", "Công ty Cổ phần Giống bò sữa Mộc Châu", "HOSE"),
    ("MCP", "Công ty Cổ phần In và Bao bì Mỹ Châu", "HOSE"),
    ("MDG", "Công ty Cổ phần Miền Đông", "HOSE"),
    ("MHC", "Công ty Cổ phần MHC", "HOSE"),
    ("MIG", "Tổng Công ty Cổ phần Bảo hiểm Quân đội", "HOSE"),
    ("MSB", "Ngân hàng Thương mại Cổ phần Hàng Hải Việt Nam", "HOSE"),
    ("MSH", "Công ty Cổ phần May Sông Hồng", "HOSE"),
    ("MSN", "Công ty Cổ phần Tập đoàn MaSan", "HOSE"),
    ("MWG", "Công ty Cổ phần Đầu tư Thế Giới Di Động", "HOSE"),
    ("MZG", "Công ty Cổ phần Miza", "HOSE"),
    ("NAB", "Ngân hàng Thương mại Cổ phần Nam Á", "HOSE"),
    ("NAF", "Công ty Cổ phần Nafoods Group", "HOSE"),
    ("NAV", "Công ty Cổ phần Nam Việt", "HOSE"),
    ("NBB", "Công ty Cổ phần Đầu tư Năm Bảy Bảy", "HOSE"),
    ("NCT", "Công ty Cổ phần Dịch vụ Hàng hóa Nội Bài", "HOSE"),
    ("NHA", "Tổng Công ty Đầu tư Phát triển Nhà và Đô thị Nam Hà Nội", "HOSE"),
    ("NHH", "Công ty Cổ phần Nhựa Hà Nội", "HOSE"),
    ("NHT", "Công ty Cổ phần Sản xuất và Thương mại Nam Hoa", "HOSE"),
    ("NKG", "Công ty Cổ phần Thép Nam Kim", "HOSE"),
    ("NLG", "Công ty Cổ phần Đầu tư Nam Long", "HOSE"),
    ("NNC", "Công ty Cổ phần Đá Núi Nhỏ", "HOSE"),
    ("NSC", "Công ty Cổ phần Tập đoàn Giống cây trồng Việt Nam", "HOSE"),
    ("NTC", "Công ty cổ phần Khu Công nghiệp Nam Tân Uyên", "HOSE"),
    ("NTL", "Công ty Cổ phần Phát triển Đô thị Từ Liêm", "HOSE"),
    ("NVL", "Công ty Cổ phần Tập đoàn Đầu tư Địa ốc No Va", "HOSE"),
    ("NVT", "Công ty Cổ phần Bất động sản Du lịch Ninh Vân Bay", "HOSE"),
    ("OCB", "Ngân hàng Thương mại Cổ phần Phương Đông", "HOSE"),
    ("OGC", "Công ty Cổ phần Tập đoàn Đại Dương", "HOSE"),
    ("OPC", "Công ty Cổ phần Dược phẩm OPC", "HOSE"),
    ("ORS", "Công ty Cổ phần Chứng khoán Tiên Phong", "HOSE"),
    ("PAC", "Công ty Cổ phần Pin Ắc quy miền Nam", "HOSE"),
    ("PAN", "Công ty Cổ phần Tập đoàn PAN", "HOSE"),
    ("PDN", "Công ty Cổ phần Cảng Đồng Nai", "HOSE"),
    ("PDR", "Công ty Cổ phần Phát triển Bất động sản Phát Đạt", "HOSE"),
    ("PDV", "Công ty Cổ phần Vận tải và Tiếp vận Phương Đông Việt", "HOSE"),
    ("PET", "Tổng Công ty Cổ phần Dịch vụ Tổng hợp Dầu khí", "HOSE"),
    ("PGC", "Tổng Công ty Gas Petrolimex - Công ty Cổ phần", "HOSE"),
    ("PGD", "Công ty Cổ phần Phân phối Khí thấp áp Dầu khí Việt Nam", "HOSE"),
    ("PGI", "Tổng Công ty Cổ phần Bảo hiểm Petrolimex", "HOSE"),
    ("PGV", "Tổng Công ty Phát điện 3 - Công ty Cổ phần", "HOSE"),
    ("PHC", "Công ty Cổ phần Xây dựng Phục Hưng Holdings", "HOSE"),
    ("PHR", "Công ty Cổ phần Cao su Phước Hòa", "HOSE"),
    ("PIT", "Công ty Cổ phần Xuất nhập khẩu Petrolimex", "HOSE"),
    ("PJT", "Công ty Cổ phần Vận tải Xăng dầu Đường thủy Petrolimex", "HOSE"),
    ("PLP", "Công ty Cổ phần Sản xuất và Công nghệ Nhựa Pha Lê", "HOSE"),
    ("PLX", "Tập đoàn Xăng dầu Việt Nam", "HOSE"),
    ("PMG", "Công ty Cổ phần Đầu tư và Sản xuất Petro Miền Trung", "HOSE"),
    ("PNC", "Công ty Cổ phần Văn hóa Phương Nam", "HOSE"),
    ("PNJ", "Công ty Cổ phần Vàng bạc Đá quý Phú Nhuận", "HOSE"),
    ("POW", "Tổng Công ty Điện lực Dầu khí Việt Nam - CTCP", "HOSE"),
    ("PPC", "Công ty Cổ phần Nhiệt điện Phả Lại", "HOSE"),
    ("PTB", "Công ty Cổ phần Phú Tài", "HOSE"),
    ("PTC", "Công ty Cổ phần Đầu tư iCapital", "HOSE"),
    ("PTL", "Công ty Cổ phần Victory Group", "HOSE"),
    ("PVD", "Tổng Công ty Cổ phần Khoan và Dịch vụ Khoan Dầu khí", "HOSE"),
    ("PVP", "Công ty Cổ phần Vận tải Dầu khí Thái Bình Dương", "HOSE"),
    ("PVT", "Tổng Công ty Cổ phần Vận tải Dầu khí", "HOSE"),
    ("QCG", "Công ty Cổ phần Quốc Cường Gia Lai", "HOSE"),
    ("QNP", "Công ty Cổ phần Cảng Quy Nhơn", "HOSE"),
    ("RAL", "Công ty Cổ phần Bóng đèn Phích nước Rạng Đông", "HOSE"),
    ("REE", "Công ty Cổ phần Cơ Điện Lạnh", "HOSE"),
    ("RYG", "Công ty Cổ phần Sản xuất và Đầu tư Hoàng Gia", "HOSE"),
    ("SAB", "Tổng Công ty Cổ phần Bia – Rượu – Nước giải khát Sài Gòn", "HOSE"),
    ("SAM", "Công ty Cổ phần SAM Holdings", "HOSE"),
    ("SAV", "Công ty Cổ phần Hợp tác Kinh tế và Xuất nhập khẩu Savimex", "HOSE"),
    ("SBA", "Công ty Cổ phần Sông Ba", "HOSE"),
    ("SBG", "Công ty Cổ phần Tập đoàn Cơ khí Công nghệ cao Siba", "HOSE"),
    ("SBT", "Công ty Cổ phần Thành Thành Công - Biên Hòa", "HOSE"),
    ("SBV", "Công ty Cổ phần Siam Brothers Việt Nam", "HOSE"),
    ("SCR", "Công ty Cổ phần Địa ốc Sài Gòn Thương Tín", "HOSE"),
    ("SCS", "Công ty Cổ phần Dịch vụ Hàng hóa Sài Gòn", "HOSE"),
    ("SFC", "Công ty Cổ phần Nhiên liệu Sài Gòn", "HOSE"),
    ("SFG", "Công ty Cổ phần Phân bón Miền Nam", "HOSE"),
    ("SFI", "Công ty Cổ phần Đại lý Vận tải SAFI", "HOSE"),
    ("SGN", "Công ty Cổ phần Phục vụ Mặt đất Sài Gòn", "HOSE"),
    ("SGR", "Công ty Cổ phần Tổng Công ty Cổ phần Địa ốc Sài Gòn", "HOSE"),
    ("SGT", "Công ty Cổ phần Công nghệ Viễn thông Sài Gòn", "HOSE"),
    ("SHA", "Công ty Cổ phần Sơn Hà Sài Gòn", "HOSE"),
    ("SHB", "Ngân hàng Thương mại Cổ phần Sài Gòn – Hà Nội", "HOSE"),
    ("SHI", "Công ty Cổ phần Quốc tế Sơn Hà", "HOSE"),
    ("SHP", "Công ty Cổ phần Thủy điện Miền Nam", "HOSE"),
    ("SIP", "Công ty Cổ phần Đầu tư Sài Gòn VRG", "HOSE"),
    ("SJD", "Công ty Cổ phần Thủy điện Cần Đơn", "HOSE"),
    ("SJS", "Công ty Cổ phần SJ Group", "HOSE"),
    ("SKG", "Công ty Cổ phần Tàu cao tốc Superdong – Kiên Giang", "HOSE"),
    ("SMA", "Công ty Cổ phần Thiết bị Phụ tùng Sài Gòn", "HOSE"),
    ("SMB", "Công ty Cổ phần Bia Sài Gòn - Miền Trung", "HOSE"),
    ("SMC", "Công ty Cổ phần Đầu tư Thương mại SMC", "HOSE"),
    ("SPM", "Công ty Cổ phần S.P.M", "HOSE"),
    ("SRC", "Công ty Cổ phần Cao su Sao Vàng", "HOSE"),
    ("SRF", "Công ty Cổ phần SEAREFICO", "HOSE"),
    ("SSB", "Ngân hàng Thương mại Cổ phần Đông Nam Á", "HOSE"),
    ("SSC", "Công ty Cổ phần Giống Cây trồng Miền Nam", "HOSE"),
    ("SSI", "Công ty Cổ phần Chứng khoán SSI", "HOSE"),
    ("STB", "Ngân hàng thương mại cổ phần Sài Gòn Tài Lộc", "HOSE"),
    ("STG", "Công ty Cổ phần Kho vận Miền Nam", "HOSE"),
    ("STK", "Công ty Cổ phần Sợi Thế Kỷ", "HOSE"),
    ("SVC", "Công ty Cổ phần Dịch vụ Tổng hợp Sài Gòn", "HOSE"),
    ("SVD", "Công ty Cổ phần Đầu tư & Thương mại Vũ Đăng", "HOSE"),
    ("SVT", "Công ty Cổ phần Công nghệ Sài Gòn Viễn Đông", "HOSE"),
    ("SZC", "Công ty Cổ phần Sonadezi Châu Đức", "HOSE"),
    ("SZL", "Công ty Cổ phần Sonadezi Long Thành", "HOSE"),
    ("TAL", "Công ty cổ phần Đầu tư Bất động sản Taseco", "HOSE"),
    ("TBC", "Công ty Cổ phần Thủy điện Thác Bà", "HOSE"),
    ("TCB", "Ngân hàng Thương mại Cổ phần Kỹ Thương Việt Nam", "HOSE"),
    ("TCH", "Công ty Cổ phần Đầu tư Dịch vụ Tài chính Hoàng Huy", "HOSE"),
    ("TCI", "Công ty Cổ phần Chứng khoán Thành Công", "HOSE"),
    ("TCL", "Công ty Cổ phần Đại lý Giao nhận Vận tải Xếp dỡ Tân Cảng", "HOSE"),
    ("TCM", "Công ty Cổ phần Dệt may - Đầu tư - Thương mại Thành Công", "HOSE"),
    ("TCO", "CÔNG TY CỔ PHẦN JANUS GROUP", "HOSE"),
    ("TCR", "Công ty Cổ phần Công nghiệp Gốm sứ TAICERA", "HOSE"),
    ("TCT", "Công ty Cổ phần Cáp treo Núi Bà Tây Ninh", "HOSE"),
    ("TCX", "Công ty cổ phần Chứng khoán Kỹ Thương", "HOSE"),
    ("TDC", "Công ty Cổ phần Kinh doanh và Phát triển Bình Dương", "HOSE"),
    ("TDG", "Công ty Cổ phần Đầu tư TDG GLOBAL", "HOSE"),
    ("TDH", "Công ty Cổ phần Phát triển Nhà Thủ Đức", "HOSE"),
    ("TDM", "Công ty Cổ phần Nước Thủ Dầu Một", "HOSE"),
    ("TDP", "Công ty Cổ phần Thuận Đức", "HOSE"),
    ("TDW", "Công ty Cổ phần Cấp nước Thủ Đức", "HOSE"),
    ("TEG", "Công ty Cổ phần Trường Thành Energy Group", "HOSE"),
    ("THG", "Công ty Cổ phần Đầu tư và Xây dựng Tiền Giang", "HOSE"),
    ("TIP", "Công ty Cổ phần Phát triển Khu Công nghiệp Tín Nghĩa", "HOSE"),
    ("TIX", "Công ty Cổ phần Sản xuất Kinh doanh XNK Dịch vụ và Đầu tư Tân Bình", "HOSE"),
    ("TLD", "Công ty Cổ phần Đầu tư Xây dựng và Phát triển Đô thị Thăng Long", "HOSE"),
    ("TLG", "Công ty Cổ phần Tập đoàn Thiên Long", "HOSE"),
    ("TLH", "Công ty Cổ phần Tập đoàn Thép Tiến Lên", "HOSE"),
    ("TMP", "Công ty Cổ phần Thủy điện Thác Mơ", "HOSE"),
    ("TMS", "Công ty Cổ phần Transimex", "HOSE"),
    ("TMT", "Công ty Cổ phần Ô tô TMT", "HOSE"),
    ("TNC", "Công ty Cổ phần Cao su Thống Nhất", "HOSE"),
    ("TNH", "Công ty Cổ phần Tập đoàn Bệnh viện TNH", "HOSE"),
    ("TNI", "Công ty Cổ phần Tập đoàn Thành Nam", "HOSE"),
    ("TNT", "Công ty Cổ phần Tập đoàn TNT", "HOSE"),
    ("TPB", "Ngân hàng Thương mại Cổ phần Tiên Phong", "HOSE"),
    ("TPC", "Công ty Cổ phần Nhựa Tân Đại Hưng", "HOSE"),
    ("TRA", "Công ty Cổ phần Traphaco", "HOSE"),
    ("TRC", "Công ty Cổ phần Cao su Tây Ninh", "HOSE"),
    ("TSA", "Công ty Cổ phần Đầu tư và Xây lắp Trường Sơn", "HOSE"),
    ("TSC", "Công ty Cổ phần Vật tư Kỹ thuật Nông nghiệp Cần Thơ", "HOSE"),
    ("TTA", "Công ty Cổ phần Đầu tư Xây dựng và Phát triển Trường Thành", "HOSE"),
    ("TTE", "Công ty Cổ phần Đầu tư Năng lượng Trường Thịnh", "HOSE"),
    ("TTF", "Công ty Cổ phần Tập đoàn Kỹ nghệ Gỗ Trường Thành", "HOSE"),
    ("TVB", "Công ty Cổ phần Chứng khoán T-Cap", "HOSE"),
    ("TVS", "Công ty Cổ phần Chứng khoán Thiên Việt", "HOSE"),
    ("TVT", "Tổng Công ty Việt Thắng - CTCP", "HOSE"),
    ("TYA", "Công ty Cổ phần Dây và Cáp điện Taya Việt Nam", "HOSE"),
    ("UIC", "Công ty Cổ phần Đầu tư Phát triển Nhà và Đô thị IDICO", "HOSE"),
    ("VAB", "Ngân hàng Thương mại cổ phần Việt Á", "HOSE"),
    ("VBB", "Ngân hàng Thương mại Cổ phần Việt Nam Thương Tín", "HOSE"),
    ("VCA", "Công ty Cổ phần Thép VICASA", "HOSE"),
    ("VCB", "Ngân hàng Thương mại Cổ phần Ngoại Thương Việt Nam", "HOSE"),
    ("VCF", "Công ty Cổ phần VINACAFÉ Biên Hòa", "HOSE"),
    ("VCG", "Tổng Công ty Cổ phần Xuất nhập khẩu và Xây dựng Việt Nam", "HOSE"),
    ("VCI", "Công ty Cổ phần Chứng khoán Vietcap", "HOSE"),
    ("VCK", "Công ty Cổ phần Chứng khoán VPS", "HOSE"),
    ("VDP", "Công ty Cổ phần Dược phẩm Trung Ương Vidipha", "HOSE"),
    ("VDS", "Công ty Cổ phần Chứng khoán Rồng Việt", "HOSE"),
    ("VFG", "Công ty Cổ phần Khử trùng Việt Nam", "HOSE"),
    ("VGC", "Tổng Công ty Viglacera - CTCP", "HOSE"),
    ("VHC", "Công ty Cổ phần Vĩnh Hoàn", "HOSE"),
    ("VHM", "Công ty Cổ phần Vinhomes", "HOSE"),
    ("VIB", "Ngân hàng Thương mại Cổ phần Quốc tế Việt Nam", "HOSE"),
    ("VIC", "Tập đoàn Vingroup - Công ty Cổ phần", "HOSE"),
    ("VID", "Công ty Cổ phần Đầu tư Phát triển Thương mại Viễn Đông", "HOSE"),
    ("VIP", "Công ty Cổ phần Vận tải Xăng dầu VIPCO", "HOSE"),
    ("VIX", "Công ty Cổ phần Chứng khoán VIX", "HOSE"),
    ("VJC", "Công ty Cổ phần Hàng không VietJet", "HOSE"),
    ("VMD", "Công ty Cổ phần Y Dược phẩm Vimedimex", "HOSE"),
    ("VND", "Công ty Cổ phần Chứng khoán VNDIRECT", "HOSE"),
    ("VNG", "Công ty Cổ phần Du lịch Thành Thành Công", "HOSE"),
    ("VNL", "Công ty Cổ phần Logistics Vinalink", "HOSE"),
    ("VNM", "Công ty Cổ phần Sữa Việt Nam", "HOSE"),
    ("VNS", "Công ty Cổ phần Ánh Dương Việt Nam", "HOSE"),
    ("VOS", "Công ty Cổ phần Vận tải Biển Việt Nam", "HOSE"),
    ("VPB", "Ngân hàng Thương mại Cổ phần Việt Nam Thịnh Vượng", "HOSE"),
    ("VPD", "Công ty Cổ phần Phát triển Điện lực Việt Nam", "HOSE"),
    ("VPG", "Công ty Cổ phần Đầu tư Thương mại Xuất nhập khẩu Việt Phát", "HOSE"),
    ("VPH", "Công ty Cổ phần Vạn Phát Hưng", "HOSE"),
    ("VPI", "Công ty Cổ phần Phát triển BĐS Văn Phú", "HOSE"),
    ("VPL", "Công ty cổ phần Vinpearl", "HOSE"),
    ("VPS", "Công ty Cổ phần Thuốc sát trùng Việt Nam", "HOSE"),
    ("VPX", "Công ty cổ phần Chứng khoán VPBANK", "HOSE"),
    ("VRC", "Công ty Cổ phần Bất động sản và Đầu tư VRC", "HOSE"),
    ("VRE", "Công ty Cổ phần Vincom Retail", "HOSE"),
    ("VSC", "Công ty Cổ phần Container Việt Nam", "HOSE"),
    ("VSH", "Công ty Cổ phần Thủy điện Vĩnh Sơn - Sông Hinh", "HOSE"),
    ("VSI", "Công ty Cổ phần Đầu tư và Xây dựng Cấp thoát nước", "HOSE"),
    ("VTB", "Công ty Cổ phần Viettronics Tân Bình", "HOSE"),
    ("VTO", "Công ty Cổ phần Vận tải Xăng dầu VITACO", "HOSE"),
    ("VTP", "Tổng Công ty Cổ phần Bưu chính Viettel", "HOSE"),
    ("VVS", "Công ty cổ phần Đầu tư phát triển máy Việt Nam", "HOSE"),
    ("YBM", "Công ty Cổ phần Khoáng sản Công nghiệp Yên Bái", "HOSE"),
    ("YEG", "Công ty Cổ phần Tập đoàn Yeah1", "HOSE"),
    ("AAH", "CTCP Hop nhat", "UPCOM"),
    ("AAS", "CTCP Chứng khoán SmartInvest", "UPCOM"),
    ("AAV", "Cổ phiếu Công ty cổ phần AAV Group", "UPCOM"),
    ("ABB", "NHTMCP An Binh", "UPCOM"),
    ("ABC", "CP CTCP Truyen thong VMG", "UPCOM"),
    ("ABI", "Cổ phiếu CTCP Bảo hiểm Ngân hàng Nông nghiệp", "UPCOM"),
    ("ABW", "CTCP Chung khoan An Binh", "UPCOM"),
    ("ACE", "Cổ phiếu CTCP Bê tông Ly tâm An Giang", "UPCOM"),
    ("ACM", "CTCP Tap doan Khoang san A Cuong", "UPCOM"),
    ("ACS", "CTCP Xay lap Thuong mai 2", "UPCOM"),
    ("ACV", "Tong cong ty Cang hang khong Viet Nam", "UPCOM"),
    ("AGF", "CTCP Xuat nhap khau Thuy san An Giang", "UPCOM"),
    ("AGM", "Cổ phiếu Công ty cổ phần Xuất nhập khẩu An Giang", "UPCOM"),
    ("AGP", "CTCP Duoc Agimexpham", "UPCOM"),
    ("AGX", "CTCP Thực phẩm Nông sản Xuất khẩu Sài Gòn", "UPCOM"),
    ("AIC", "Công ty cổ phần Tập đoàn Bảo hiểm DBV", "UPCOM"),
    ("AIG", "CTCP Nguyen lieu A Chau AIG", "UPCOM"),
    ("ALC", "Cổ phiếu Công ty cổ phần Âu Lạc", "UPCOM"),
    ("ALV", "Công ty cổ phần Tập đoàn MCST", "UPCOM"),
    ("AMP", "CTCP Armephaco", "UPCOM"),
    ("AMS", "CTCP Co khi Xay dung AMECC", "UPCOM"),
    ("ANI", "Cổ phiếu Công ty cổ phần ANI", "UPCOM"),
    ("APC", "CTCP chieu xa An Phu", "UPCOM"),
    ("APF", "CTCP Nong san Thuc pham Quang Ngai", "UPCOM"),
    ("APL", "CTCP Co khi va Thiet bi ap luc VVMI", "UPCOM"),
    ("APP", "APP - CTCP Phát triển Phụ gia và Sản phẩm Dầu mỏ", "UPCOM"),
    ("APT", "CTCP Kinh doanh Thủy hải sản Sài Gòn", "UPCOM"),
    ("ART", "Công ty cổ phần Chứng khoán BOS", "UPCOM"),
    ("ATA", "CTCP NTACO", "UPCOM"),
    ("ATG", "Công ty Cổ phần ATG Planet", "UPCOM"),
    ("AVC", "CTCP Thuy dien A Vuong", "UPCOM"),
    ("AVG", "Công ty cổ phần Phân bón Quốc tế Âu Việt", "UPCOM"),
    ("BAL", "CTCP Bao bi Bia - Ruou - Nuoc giai khat", "UPCOM"),
    ("BBH", "CTCP Bao bì Hoàng Thạch", "UPCOM"),
    ("BBM", "CTCP Bia Ha noi - Nam dinh", "UPCOM"),
    ("BBT", "CTCP Bông Bạch Tuyết", "UPCOM"),
    ("BCA", "CTCP B.C.H", "UPCOM"),
    ("BCB", "CTCP 397", "UPCOM"),
    ("BCP", "Công ty cổ phần Dược Enlie", "UPCOM"),
    ("BCR", "CTCP BCG Land", "UPCOM"),
    ("BCV", "CTCP Du lịch và Thương mại Bằng Giang Cao Bằng - Vimico", "UPCOM"),
    ("BDG", "CTCP May mac Binh Duong", "UPCOM"),
    ("BDT", "Công ty cổ phần Xây lắp và Vật liệu Xây dựng Đồng Tháp", "UPCOM"),
    ("BDW", "CTCP Cap thoat nuoc Binh Dinh", "UPCOM"),
    ("BEL", "CTCP Dien tu Bien Hoa", "UPCOM"),
    ("BGE", "Công ty cổ phần BCG Energy", "UPCOM"),
    ("BGW", "BGW - CTCP Nước sạch Bắc Giang", "UPCOM"),
    ("BHA", "CTCP Thủy điện Bắc Hà", "UPCOM"),
    ("BHC", "Cổ phiếu Công ty Cổ phần Bê tông Biên Hòa", "UPCOM"),
    ("BHG", "Công ty cổ phần Chè Biển Hồ", "UPCOM"),
    ("BHH", "Cổ phiếu Công ty cổ phần Thương mại Bia Hà Nội - Hưng Yên 89", "UPCOM"),
    ("BHI", "Tổng Công ty cổ phần Bảo hiểm Sài Gòn - Hà Nội", "UPCOM"),
    ("BHK", "CTCP Bia Ha Noi - Kim Bai", "UPCOM"),
    ("BHP", "Cổ phiếu CTCP Bia Hà Nội - Hải Phòng", "UPCOM"),
    ("BIG", "Công ty cổ phần Đầu tư Big Group Holdings", "UPCOM"),
    ("BIO", "CTCP Vac Xin va Sinh pham Nha Trang", "UPCOM"),
    ("BLF", "Cổ phiếu CTCP Thuỷ sản Bạc Liêu", "UPCOM"),
    ("BLI", "CTCP Bao hiem Bao Long", "UPCOM"),
    ("BLN", "CTCP Van tai va Dich vu Lien Ninh", "UPCOM"),
    ("BLT", "CTCP Lương thực Bình Định", "UPCOM"),
    ("BMD", "CTCP Moi truong va Dich vu do thi Binh Thuan", "UPCOM"),
    ("BMF", "CTCP Vat lieu Xay dung va Chat dot Dong Nai", "UPCOM"),
    ("BMG", "CTCP May Bình Minh", "UPCOM"),
    ("BMJ", "Công ty cổ phần Khoáng sản miền đông AHP", "UPCOM"),
    ("BMK", "Công ty cổ phần Kỹ thuật nhiệt Mèo Đen", "UPCOM"),
    ("BMS", "CTCP Chung khoan Bao Minh", "UPCOM"),
    ("BMV", "CTCP Bot my Vinafood 1", "UPCOM"),
    ("BNW", "CTCP nuoc sach Bac Ninh", "UPCOM"),
    ("BOT", "CTCP BOT Cau Thai Ha", "UPCOM"),
    ("BQB", "CTCP Bia Ha Noi - Quang Binh", "UPCOM"),
    ("BQP", "Cổ phiếu Công ty cổ phần Nhựa Chất lượng cao Bình Thuận", "UPCOM"),
    ("BRR", "CTCP Cao su Ba Ria", "UPCOM"),
    ("BRS", "CTCP Dich vu Do thi Ba Ria", "UPCOM"),
    ("BSA", "CTCP Thuy dien Buon Don", "UPCOM"),
    ("BSD", "CTCP Bia, Ruou Sai Gon - Dong Xuan", "UPCOM"),
    ("BSG", "CTCP Xe khach Sai Gon", "UPCOM"),
    ("BSH", "CTCP Bia Sai Gon - Ha noi", "UPCOM"),
    ("BSL", "CTCP Bia Sai Gon - Song Lam", "UPCOM"),
    ("BSP", "Công ty CP Bia Sài Gòn - Phú Thọ", "UPCOM"),
    ("BSQ", "BSQ- CTCP Bia Sai Gon-Quang Ngai", "UPCOM"),
    ("BTB", "CTCP Bia Ha Noi - Thai Binh", "UPCOM"),
    ("BTD", "Công ty cổ phần Bê tông ly tâm Thủ Đức", "UPCOM"),
    ("BTG", "Cổ phiếu CTCP Bao bì Tiền Giang", "UPCOM"),
    ("BTH", "Cổ phiếu CTCP Chế tạo Biến thế  và  Vật liệu điện Hà nội", "UPCOM"),
    ("BTN", "Công ty cổ phần Đầu tư Bitco Bình Định", "UPCOM"),
    ("BTU", "CTCP Cong trinh Do thi Ben Tre", "UPCOM"),
    ("BTV", "BTV- ctcp dich vu Du lich Ben Thanh", "UPCOM"),
    ("BVG", "Công ty cổ phần Group Bắc Việt", "UPCOM"),
    ("BVL", "CTCP BV Land", "UPCOM"),
    ("BVN", "BVN - Công ty cổ phần Bông Việt Nam", "UPCOM"),
    ("BWA", "Cổ phiếu CTCP Cấp thoát nước và Xây dựng Bảo Lộc", "UPCOM"),
    ("BWS", "CTCP Cap nuoc Ba Ria - Vung Tau", "UPCOM"),
    ("CAD", "Cổ phiếu CTCP chế biến và XNK thuỷ sản Cadovimex", "UPCOM"),
    ("CAT", "CTCP Thuy san Ca Mau", "UPCOM"),
    ("CBI", "CTCP Gang thep Cao Bang", "UPCOM"),
    ("CBS", "CTCP Mia duong Cao Bang", "UPCOM"),
    ("CCA", "CTCP xuất nhập khẩu Thủy sản Cần thơ", "UPCOM"),
    ("CCM", "Công ty cổ phần Khoáng sản và Xi măng Cần Thơ", "UPCOM"),
    ("CCP", "CTCP Cang Cua Cam Hai Phong", "UPCOM"),
    ("CCS", "CTCP Chíp Sáng", "UPCOM"),
    ("CCT", "CTCP CANG CAN THO", "UPCOM"),
    ("CCV", "CTCP Tu van Xay dung Cong nghiep va Do thi Vietnam", "UPCOM"),
    ("CDG", "CDG- CTCP Cau Duong", "UPCOM"),
    ("CDO", "CTCP Tu van thiet ke va Phat trien do thi", "UPCOM"),
    ("CDP", "CTCP Duoc pham Trung uong Codupha", "UPCOM"),
    ("CDR", "CTCP Xây dựng Cao su Đồng Nai", "UPCOM"),
    ("CEN", "CTCP CENCON Việt Nam", "UPCOM"),
    ("CFM", "CTCP Dau tu CFM", "UPCOM"),
    ("CFV", "Công ty cổ phần Cà phê Thắng Lợi", "UPCOM"),
    ("CGV", "Công ty cổ phần Vinaceglass", "UPCOM"),
    ("CHC", "Công ty cổ phần Cẩm Hà", "UPCOM"),
    ("CHS", "CTCP Chieu sang cong cong TPHCM", "UPCOM"),
    ("CID", "Cổ phiếu CTCP Xây dựng & Phát triển Cơ sở hạ tầng", "UPCOM"),
    ("CIP", "CTCP Xay lap va San xuat Cong nghiep", "UPCOM"),
    ("CKA", "CTCP Cơ khí An Giang", "UPCOM"),
    ("CKD", "Công ty Cổ phần Cơ khí Đông Anh Licogi", "UPCOM"),
    ("CLI", "Cổ phiếu Công ty cổ phần Tập đoàn CNCTech", "UPCOM"),
    ("CLX", "Công ty cổ phần Xuất nhập khẩu và Đầu tư Chợ Lớn", "UPCOM"),
    ("CMD", "CTCP Vật liệu Xây dựng và Trang trí nội thất TP.Hồ Chí Minh", "UPCOM"),
    ("CMF", "CTCP Thuc pham Cholimex", "UPCOM"),
    ("CMI", "Công ty cổ phần CMISTONE Việt Nam", "UPCOM"),
    ("CMK", "CTCP Co khi Mao Khe - Vinacomin", "UPCOM"),
    ("CMM", "CTCP Camimex", "UPCOM"),
    ("CMN", "Công ty cổ phần Lương thực thực phẩm Colusa- Miliket", "UPCOM"),
    ("CMP", "CTCP Cang Chan May", "UPCOM"),
    ("CMT", "CTCP Công nghệ Mạng và Truyền thông", "UPCOM"),
    ("CMW", "CTCP Cap nuoc Ca Mau", "UPCOM"),
    ("CNA", "Công ty cổ phần Tổng công ty Chè Nghệ An", "UPCOM"),
    ("CNC", "CTCP Công nghệ cao Traphaco", "UPCOM"),
    ("CNN", "CTCP Tu van cong nghe, thiet bi va kiem dinh xay dung Coninco", "UPCOM"),
    ("CNT", "Công ty cổ phần Tập đoàn CNT", "UPCOM"),
    ("CPA", "CTCP Ca phe Phuoc An", "UPCOM"),
    ("CPH", "CTCP Phuc Vu Mai tang Hai Phong", "UPCOM"),
    ("CPI", "CTCP Dau tu Cang Cai Lan", "UPCOM"),
    ("CQN", "CTCP Cảng Quảng Ninh", "UPCOM"),
    ("CQT", "CTCP Xi măng Quán Triều VVMI", "UPCOM"),
    ("CSI", "Công ty cổ phần Chứng khoán Kirin", "UPCOM"),
    ("CTW", "CTCP Cap thoat nuoc Can Tho", "UPCOM"),
    ("CTX", "Cổ phiếu Tổng Công ty cổ phần Đầu tư xây dựng và Thương mại Việt Nam", "UPCOM"),
    ("CVN", "Cổ phiếu Công ty cổ phần Vinam", "UPCOM"),
    ("CYC", "CTCP Gach men Chang Yih", "UPCOM"),
    ("DAC", "Công ty cổ phần 382 Đông Anh", "UPCOM"),
    ("DAG", "CTCP Tập đoàn Nhựa Đông Á", "UPCOM"),
    ("DAN", "CTCP Duoc Danapha", "UPCOM"),
    ("DAS", "CTCP Máy - Thiết bị Dầu khí Đà Nẵng", "UPCOM"),
    ("DBM", "Cổ phiếu CTCP Dược - Vật tư Y tế Đăk Lăk", "UPCOM"),
    ("DCF", "CTCP Xay dung va Thiet ke so 1", "UPCOM"),
    ("DCG", "CTCP Tổng công ty May Đáp Cầu", "UPCOM"),
    ("DCH", "CTCP Dia chinh Ha noi", "UPCOM"),
    ("DCR", "CTCP Gach men Cosevco", "UPCOM"),
    ("DCS", "Cong ty co phan Tap doan Dai Chau", "UPCOM"),
    ("DCT", "CTCP Tam lop Vat lieu Xay dung Dong Nai", "UPCOM"),
    ("DCV", "Cổ phiếu CTCP Quản lý quỹ Đầu tư Dragon Capital Việt Nam", "UPCOM"),
    ("DDB", "CTCP Thương mại và Xây dựng Đông Dương", "UPCOM"),
    ("DDG", "Cổ phiếu Công ty cổ phần Đầu tư Công nghiệp Xuất nhập khẩu Đông Dương", "UPCOM"),
    ("DDH", "CTCP Dam bao giao thong duong thuy Hai Phong", "UPCOM"),
    ("DDM", "Cổ Phiếu CTCP Hàng Hải Đông Đô", "UPCOM"),
    ("DDN", "Cổ phiếu CTCP Dược - Thiết bị Y tế Đà Nẵng", "UPCOM"),
    ("DDV", "CTCP DAP - VINACHEM", "UPCOM"),
    ("DFC", "CTCP Xich lip Dong Anh", "UPCOM"),
    ("DFF", "CTCP Tập đoàn Đua Fat", "UPCOM"),
    ("DGT", "Cổ phiếu CTCP Công trình giao thông Đồng Nai", "UPCOM"),
    ("DHB", "CTCP Phan dam va Hoa chat Ha Bac", "UPCOM"),
    ("DHD", "CTCP Duoc Vat tu Y te Hai Duong", "UPCOM"),
    ("DHN", "CTCP Duoc pham Ha Noi", "UPCOM"),
    ("DIC", "CTCP Đầu tư và Thương mại DIC", "UPCOM"),
    ("DID", "Cổ phiếu CTCP DIC - Đồng Tiến", "UPCOM"),
    ("DKC", "CTCP Cho Lang Son", "UPCOM"),
    ("DKG", "Công ty cổ phần Tập đoàn Damik", "UPCOM"),
    ("DLD", "Cổ phiếu CTCP Du Lịch Đắk Lắk", "UPCOM"),
    ("DLR", "Cổ phiếu CTCP Địa ốc Đà Lạt", "UPCOM"),
    ("DLT", "CTCP Du lich va Thuong mai - Vinacomin", "UPCOM"),
    ("DMN", "CTCP Domenal", "UPCOM"),
    ("DNA", "CTCP Điện nước An Giang", "UPCOM"),
    ("DND", "CTCP Dau tu xay dung va Vat lieu Dong nai", "UPCOM"),
    ("DNE", "CTCP Moi truong Do thi Da Nang", "UPCOM"),
    ("DNH", "CTCP Thuy dien Da Nhim - Ham Thuan - Da Mi", "UPCOM"),
    ("DNL", "Cổ phiếu Công ty Cổ phần Logistics Cảng Đà Nẵng", "UPCOM"),
    ("DNM", "DNM - Tổng Công ty Cổ phần Y tế Danameco", "UPCOM"),
    ("DNN", "CTCP Cap nuoc Da Nang", "UPCOM"),
    ("DNT", "Cổ phiếu CTCP Du lịch Đồng Nai", "UPCOM"),
    ("DNW", "CTCP Cap nuoc Dong Nai", "UPCOM"),
    ("DOC", "CTCP Vat tu nong nghiep Dong Nai", "UPCOM"),
    ("DOP", "Công ty cổ phần Vận tải Xăng dầu Đồng Tháp", "UPCOM"),
    ("DPC", "Cổ phiếu Công ty Cổ phần Nhựa Đà Nẵng", "UPCOM"),
    ("DPH", "CTCP Duoc pham Hai Phong", "UPCOM"),
    ("DPP", "Cổ phiếu CTCP Dược Đồng Nai", "UPCOM"),
    ("DRG", "CTCP Cao su Đắk Lắk", "UPCOM"),
    ("DRI", "CTCP Dau tu Cao su Dak Lak", "UPCOM"),
    ("DSD", "CTCP DHC Suoi Doi", "UPCOM"),
    ("DSG", "Công ty cổ phần Kính Đáp Cầu", "UPCOM"),
    ("DSH", "Công ty cổ phần Đông Sơn Holdings", "UPCOM"),
    ("DSP", "CTCP Dịch vụ Du lịch Phú Thọ", "UPCOM"),
    ("DTC", "Cổ phiếu CTCP Viglacera  Đông Triều", "UPCOM"),
    ("DTH", "CTCP Duoc Vat tu Y te Thanh Hoa", "UPCOM"),
    ("DTI", "CTCP Dau tu Duc Trung", "UPCOM"),
    ("DTP", "CTCP Dược phẩm CPC1 Hà Nội", "UPCOM"),
    ("DUS", "CTCP Dịch vụ Đô thị Đà Lạt", "UPCOM"),
    ("DVC", "CTCP Thương mại Dịch vụ Tổng hợp Cảng Hải Phòng", "UPCOM"),
    ("DVG", "Công ty cổ phần Đại Việt Group DVG", "UPCOM"),
    ("DVN", "Tong CTCP  Duoc Viet Nam", "UPCOM"),
    ("DVT", "Cổ phiếu Công ty cổ phần Đào tạo và Dịch vụ giao thông vận tải Bình Định", "UPCOM"),
    ("DVW", "CTCP Dich vu va Xay dung Cap nuoc Dong nai", "UPCOM"),
    ("DWC", "Công ty cổ phần Cấp nước Đắc Lắk", "UPCOM"),
    ("DWS", "CTCP Cap nuoc va Moi truong do thi Dong Thap", "UPCOM"),
    ("DXL", "Cổ phiếu CTCP Du lịch và Xuất Nhập khẩu Lạng Sơn", "UPCOM"),
    ("ECO", "Công ty cổ phần Nhựa sinh thái Việt Nam", "UPCOM"),
    ("EFI", "Cổ phiếu CTCP Đầu tư Tài chính Giáo dục", "UPCOM"),
    ("EGL", "CTCP Môi trường đô thị Gia Lâm", "UPCOM"),
    ("EIC", "EIC- CTCP EVN Quoc te", "UPCOM"),
    ("EIN", "CTCP Dau tu - Thuong mai - Dich vu Dien luc", "UPCOM"),
    ("EME", "CTCP Dien Co", "UPCOM"),
    ("EMG", "CTCP Thiet bi phu tung co dien", "UPCOM"),
    ("EMS", "CTCP Tong cty chuyen phat nhanh Buu Dien", "UPCOM"),
    ("FBC", "CTCP Co khi Pho Yen", "UPCOM"),
    ("FCC", "CTCP Lien hop Thuc Pham", "UPCOM"),
    ("FCS", "FCS- CTCP Luong thuc thanh pho HCM", "UPCOM"),
    ("FGL", "Công ty cổ phần Cà phê Gia Lai", "UPCOM"),
    ("FHN", "CTCP Xuat nhap khau Luong thuc - Thuc pham Hanoi", "UPCOM"),
    ("FHS", "CTCP Phat hanh sach thanh pho Ho Chi Minh", "UPCOM"),
    ("FIC", "TCT Vật liệu xây dựng số 1 - CTCP", "UPCOM"),
    ("FOC", "CTCP Dịch vụ Trực tuyến FPT", "UPCOM"),
    ("FOX", "CTCP vien thong FPT", "UPCOM"),
    ("FRC", "CTCP Lâm đặc sản xuất khẩu Quảng Nam", "UPCOM"),
    ("FRM", "CTCP Lam nghiep Sai gon", "UPCOM"),
    ("FSO", "CTCP Co khi dong tau thuy san Viet Nam", "UPCOM"),
    ("FTI", "CTCP Cong nghiep - Thuong mai Huu Nghi", "UPCOM"),
    ("FTM", "CTCP Dau tu va phat trien Duc Quan", "UPCOM"),
    ("GCB", "CTCP Petec Binh Dinh", "UPCOM"),
    ("GCF", "Cong ty co phan Thuc pham G.C", "UPCOM"),
    ("GDA", "CTCP Ton Dong A", "UPCOM"),
    ("GDH", "Cổ phiếu Công ty cổ phần Tập đoàn GDC", "UPCOM"),
    ("GER", "Cổ phiếu CTCP Thể Thao Ngôi sao Geru", "UPCOM"),
    ("GGG", "Cổ phiếu Công ty cổ phần Ô tô Giải Phóng", "UPCOM"),
    ("GLC", "CTCP Vàng Lào Cai", "UPCOM"),
    ("GLW", "Công ty cổ phần Cấp thoát nước Gia Lai", "UPCOM"),
    ("GMC", "CTCP Garmex SaiGon", "UPCOM"),
    ("GND", "CTCP Gach ngoi Dong nai", "UPCOM"),
    ("GPC", "CTCP Tap doan Green+", "UPCOM"),
    ("GSM", "CTCP Thủy điện Hương Sơn", "UPCOM"),
    ("GTD", "CTCP Giay Thuong Dinh", "UPCOM"),
    ("GTS", "CTCP Cong trinh Giao thong SAi Gon", "UPCOM"),
    ("GTT", "CTCP Thuan Thao", "UPCOM"),
    ("GVT", "CTCP Giay Viet Tri", "UPCOM"),
    ("HAC", "CTCPCK Hai Phong", "UPCOM"),
    ("HAF", "CTCP Thuc pham Ha Noi", "UPCOM"),
    ("HAM", "CTCP Vat tu Hau Giang", "UPCOM"),
    ("HAN", "Tổng công ty Xây dựng Hà Nội", "UPCOM"),
    ("HAV", "CTCP Ruou Hapro", "UPCOM"),
    ("HBC", "CTCP Tap doan Xay dung Hoa Binh", "UPCOM"),
    ("HBD", "CTCP Bao bì PP Bình Dương", "UPCOM"),
    ("HBH", "CTCP Habeco - Hải Phòng", "UPCOM"),
    ("HCI", "Công ty cổ phần Đầu tư - Xây dựng Hà Nội", "UPCOM"),
    ("HDM", "Cổ phiếu CTCP Dệt - May Huế", "UPCOM"),
    ("HDP", "CTCP Duoc Ha Tinh", "UPCOM"),
    ("HDW", "CTCP Kinh doanh nước sạch Hải Dương", "UPCOM"),
    ("HEC", "CTCP Tu van Xay dung Thuy loi II", "UPCOM"),
    ("HEJ", "Tong CT Tu van Xay dung Thuy loi Viet Nam", "UPCOM"),
    ("HEP", "Công ty cổ phần Môi trường và Công trình Đô thị Huế", "UPCOM"),
    ("HES", "CTCP Dich vu giai tri Ha Noi", "UPCOM"),
    ("HFB", "CTCP Cong trinh Cau pha TPHCM", "UPCOM"),
    ("HFC", "Công ty cổ phần Xăng dầu HFC", "UPCOM"),
    ("HFX", "Cổ phiếu CTCP Sản xuất - Xuất nhập khẩu Thanh Hà", "UPCOM"),
    ("HGT", "CTCP Du lich Huong Giang", "UPCOM"),
    ("HHB", "Cổ phiếu Công ty cổ phần Bia Hà Nội - Hồng Hà", "UPCOM"),
    ("HHG", "HHG - Công ty cổ phần Hoàng Hà", "UPCOM"),
    ("HHN", "CTCP Van tai va Dich vu Hang hoa HaNoi", "UPCOM"),
    ("HIO", "CTCP Helio Energy", "UPCOM"),
    ("HJC", "CTCP Hòa Việt", "UPCOM"),
    ("HKB", "HKB - CTCP Nong Nghiep va Thuc Pham Ha noi- Kinh bac", "UPCOM"),
    ("HLA", "CTCP Hữu Liên Á Châu", "UPCOM"),
    ("HLB", "Công ty Cổ phần Bia & Nước giải khát Hạ Long", "UPCOM"),
    ("HLO", "CTCP Cong nghe Ha Lo", "UPCOM"),
    ("HLS", "CTCP Sứ kỹ thuật Hoàng Liên Sơn", "UPCOM"),
    ("HLT", "Công ty cổ phần Dệt may Hoàng Thị Loan", "UPCOM"),
    ("HLY", "Công ty cổ phần gốm xây dựng Yên Hưng", "UPCOM"),
    ("HMD", "CTCP Hóa chất Minh Đức", "UPCOM"),
    ("HMG", "CTCP Kim khi Ha noi - VNSTEEL", "UPCOM"),
    ("HMS", "CTCP Xay dung Bao tang Ho Chi Minh", "UPCOM"),
    ("HNB", "CTCP Ben xe Ha Noi", "UPCOM"),
    ("HND", "Co phieu CTCP Nhiet dien Hai Phong", "UPCOM"),
    ("HNF", "CTCP Thuc pham Huu Nghi", "UPCOM"),
    ("HNG", "CTCP Nong nghiep Quoc te Hoang Anh Gia Lai", "UPCOM"),
    ("HNI", "CTCP May Huu Nghi", "UPCOM"),
    ("HNM", "CTCP Sữa Hà Nội", "UPCOM"),
    ("HNP", "CTCP Hanel Xop nhua", "UPCOM"),
    ("HNR", "Công ty Cổ phần Rượu và nước giải khát Hà Nội", "UPCOM"),
    ("HOT", "CTCP Du lich - Dich vu Hoi An", "UPCOM"),
    ("HPB", "Cổ phiếu Công ty cổ phần Bao Bì PP", "UPCOM"),
    ("HPD", "CTCP Thủy điện Đăk Đoa", "UPCOM"),
    ("HPH", "CTCP Hoa Chat Hung Phat Ha Bac", "UPCOM"),
    ("HPI", "CTCP Khu Cong nghiep Hiep Phuoc", "UPCOM"),
    ("HPO", "Cổ phiếu Công ty cổ phần Công nghiệp Hapulico", "UPCOM"),
    ("HPP", "Cổ phiếu CTCP Sơn Hải Phòng", "UPCOM"),
    ("HPT", "Cổ phiếu CTCP Dịch vụ Công nghệ Tin học HPT", "UPCOM"),
    ("HPW", "CTCP Cap nuoc Hai Phong", "UPCOM"),
    ("HRB", "CTCP Harec Dau tu va thuong mai", "UPCOM"),
    ("HSA", "CTCP HESTIA", "UPCOM"),
    ("HSM", "Tổng Công ty Cổ phần Dệt May Hà Nội", "UPCOM"),
    ("HSP", "CTCP Sơn Tổng hợp Hà Nội", "UPCOM"),
    ("HSV", "Công ty cổ phần Tập đoàn HSV Việt Nam", "UPCOM"),
    ("HTE", "CTCP Dau tu kinh doanh Dien luc TP.HCM", "UPCOM"),
    ("HTM", "CTCP Tong cong ty Thuong mai Ha noi", "UPCOM"),
    ("HTP", "Cổ phiếu CTCP In Sách giáo khoa Hoà Phát", "UPCOM"),
    ("HTT", "CTCP Thuong mai Ha Tay", "UPCOM"),
    ("HUG", "CTCP Tong cty may Hung Yen", "UPCOM"),
    ("HVA", "Công ty cổ phần Đầu tư HVA", "UPCOM"),
    ("HVX", "Cổ phiếu Công ty Cổ phần Xi măng Vicem Hải Vân", "UPCOM"),
    ("HWS", "Công ty cổ phần Cấp nước Huế", "UPCOM"),
    ("IBD", "CTCP In tong hop Thai Binh Duong", "UPCOM"),
    ("ICC", "CTCP Xay dung Cong nghiep", "UPCOM"),
    ("ICF", "CTCP Đầu tư Thương mại Thủy sản", "UPCOM"),
    ("ICI", "Cổ phiếu CTCP Đầu tư và Xây dựng Công nghiệp", "UPCOM"),
    ("ICN", "CTCP Đầu tư Xây dựng Dầu khí IDICO", "UPCOM"),
    ("IDP", "Công ty cổ phần Sữa Quốc Tế LOF", "UPCOM"),
    ("IFS", "CTCP Thuc pham Quoc te", "UPCOM"),
    ("ILA", "Công ty cổ phần ILA", "UPCOM"),
    ("ILC", "CTCP Hop tac lao dong voi nuoc ngoai", "UPCOM"),
    ("ILS", "CTCP Dau tu Thuong mai va Dich vu Quoc te", "UPCOM"),
    ("IME", "Cổ phiếu CTCP Cơ khí và Xây lắp Công nghiệp", "UPCOM"),
    ("IRC", "Công ty cổ phần Cao su Công nghiệp", "UPCOM"),
    ("ISG", "CTCP van tai bien va hop tac lao dong quoc te", "UPCOM"),
    ("ISH", "Công ty Cổ phần Thủy điện Srok Phu Miêng IDICO", "UPCOM"),
    ("IST", "CTCP ICD Tan cang Song than", "UPCOM"),
    ("ITA", "CTCP Dau tu va Cong nghiep Tan Tao", "UPCOM"),
    ("ITS", "CTCP Dau tu, Thuong mai va Dich vu - Vinacomin", "UPCOM"),
    ("JOS", "CTCP Che bien Thuy san Xuat khau Minh Hai", "UPCOM"),
    ("KCB", "Công ty cổ phần Khoáng sản và luyện kim Cao Bằng", "UPCOM"),
    ("KGM", "CTCP Xuat nhap khau Kien Giang", "UPCOM"),
    ("KHD", "CTCP khai thac, che bien khoang san Hai Duong", "UPCOM"),
    ("KHW", "Công ty cổ phần Cấp thoát nước Khánh Hòa", "UPCOM"),
    ("KHX", "Cổ phiếu Công ty cổ phần Phát hành sách Khánh Hòa", "UPCOM"),
    ("KIP", "Công ty cổ phần K.I.P Việt Nam", "UPCOM"),
    ("KPF", "Cổ phiếu Công ty cổ phần Đầu tư tài sản KOJI", "UPCOM"),
    ("KSQ", "Cổ phiếu CTCP CNC Capital Việt Nam", "UPCOM"),
    ("KTC", "CTCP Thương mại Kiên Giang", "UPCOM"),
    ("KTL", "CTCP Kim khi Thang Long", "UPCOM"),
    ("KTT", "Công ty cổ phần Tập đoàn Đầu tư KTT", "UPCOM"),
    ("KVC", "CTCP Sản xuất Xuất nhập khẩu Inox Kim Vĩ", "UPCOM"),
    ("LAI", "CTCP Dau tu xay dung Long An IDICO", "UPCOM"),
    ("LAW", "CTCP Cap thoat nuoc Long An", "UPCOM"),
    ("LCM", "CTCP Khai thác và Chế biến khoáng sản Lào cai", "UPCOM"),
    ("LDW", "Công ty Cổ phần Cấp thoát nước Lâm Đồng", "UPCOM"),
    ("LEC", "Cong ty co phan Bat dong san dien luc Mien Trung", "UPCOM"),
    ("LIC", "CTCP Tong Cong ty Licogi", "UPCOM"),
    ("LKW", "Cổ phiếu Công ty cổ phần Cấp nước Long Khánh", "UPCOM"),
    ("LLM", "CTCP Tong cong ty Lap may Viet Nam", "UPCOM"),
    ("LMC", "Công ty cổ phần Long Beach LMC", "UPCOM"),
    ("LMH", "Công ty cổ phần Quốc tế Holding", "UPCOM"),
    ("LMI", "CTCP Đầu tư Xây dựng Lắp máy IDICO", "UPCOM"),
    ("LNC", "CTCP Le Ninh", "UPCOM"),
    ("LPT", "CTCP Thuong mai va San xuat Lap Phuong Thanh", "UPCOM"),
    ("LQN", "CTCP Licogi Quảng Ngãi", "UPCOM"),
    ("LSG", "CTCP Bat dong san Saigon Vina", "UPCOM"),
    ("LTC", "Cổ phiếu CTCP Điện nhẹ Viễn Thông", "UPCOM"),
    ("LTG", "CTCP Tập đoàn Lộc Trời", "UPCOM"),
    ("LUT", "Cổ phiếu CTCP Đầu tư Xây dựng Lương Tài", "UPCOM"),
    ("MBN", "CTCP Moi truong va Cong trinh Do thi Bac Ninh", "UPCOM"),
    ("MBT", "CTCP Bat dong san cho thue Minh Bao Tin", "UPCOM"),
    ("MCG", "CTCP nang luong va bat dong san MCG", "UPCOM"),
    ("MDA", "CTCP Moi truong Do thi Dong Anh", "UPCOM"),
    ("MDF", "Công ty cổ phần gỗ MDF VRG Quảng Trị", "UPCOM"),
    ("MEC", "Cổ phiếu CTCP Cơ khí Lắp máy Sông Đà", "UPCOM"),
    ("MEF", "Cổ phiếu Công ty cổ phần MEINFA", "UPCOM"),
    ("MES", "CTCT Co dien cong trinh", "UPCOM"),
    ("MFS", "CTCP Dich vu ky thuat MobiFone", "UPCOM"),
    ("MGC", "CTCP Dia chat Mo_TKV", "UPCOM"),
    ("MGG", "CTCP tong cong ty Duc Giang", "UPCOM"),
    ("MGR", "CTCP Tap doan MGroup", "UPCOM"),
    ("MHL", "Cổ phiếu Công ty cổ phần Minh Hữu Liên", "UPCOM"),
    ("MIE", "CTCP Tong cty May va Thiet bi Cong nghiep", "UPCOM"),
    ("MKP", "CTCP Hóa - Dược phẩm Mekophar", "UPCOM"),
    ("MLC", "CTCP Moi truong Do thi tinh Lao cai", "UPCOM"),
    ("MLS", "CTCP Chan nuoi - Mitraco", "UPCOM"),
    ("MML", "CTCP Masan MeatLife", "UPCOM"),
    ("MNB", "Tổng Công ty May Nhà Bè - Công ty cổ phần", "UPCOM"),
    ("MND", "CTCP Moi truong Nam Dinh", "UPCOM"),
    ("MPC", "Công ty Cổ phần Tập đoàn Thuỷ sản Minh Phú", "UPCOM"),
    ("MPT", "Công ty cổ phần Tập đoàn MPT", "UPCOM"),
    ("MPY", "CTCP Moi truong Do thi Phu Yen", "UPCOM"),
    ("MQB", "CTCP Moi truong va Phat trien do thi Quang Binh", "UPCOM"),
    ("MQN", "CTCP Môi trường Đô thị Quảng Ngãi", "UPCOM"),
    ("MRF", "CTCP Merufa", "UPCOM"),
    ("MSR", "Công ty cổ phần Masan High - Tech Materials", "UPCOM"),
    ("MTA", "Tong cong ty Khoang san va Thuong mai Ha tinh - CTCP", "UPCOM"),
    ("MTB", "CTCP Moi truong va Cong trinh Do thi tinh Thai Binh", "UPCOM"),
    ("MTG", "MTG - CTCP MT Gas", "UPCOM"),
    ("MTH", "MTH - CTCP Môi trường Đô thị Hà Đông", "UPCOM"),
    ("MTL", "CTCP dich vu moi truong do thi Tu liem", "UPCOM"),
    ("MTP", "Công ty cổ phần Dược Medipharco", "UPCOM"),
    ("MTS", "CTCP Vat tu - TKV", "UPCOM"),
    ("MTV", "CTCP Dich vu Moi truong va Cong trinh do thi Vung Tau", "UPCOM"),
    ("MVC", "CTCP Vat lieu va Xay dung Binh Duong", "UPCOM"),
    ("MVN", "CTCP Tong cty Hang hai Viet Nam", "UPCOM"),
    ("NAC", "CTCP Tu van Xay dung tong hop", "UPCOM"),
    ("NAS", "CTCP Dich vu hang khong san bay Noi Bai", "UPCOM"),
    ("NAU", "CTCP Môi trường và Công trình đô thị Nghệ An", "UPCOM"),
    ("NAW", "CTCP Cap nuoc Nghe An", "UPCOM"),
    ("NBE", "CTCP Sach va Thiet bi Giao duc Mien Bac", "UPCOM"),
    ("NBT", "CTCP Cap thoat nuoc Ben tre", "UPCOM"),
    ("NCG", "CÔNG TY CỔ PHẦN ĐẦU TƯ ANOVA AGRI", "UPCOM"),
    ("NCS", "CTCP Suất ăn Hàng không Nội Bài", "UPCOM"),
    ("NDC", "Cổ phiếu Công ty cổ phần Nam Dược", "UPCOM"),
    ("NDF", "NDF - CTCP Che bien thuc pham nong san xuat khau Nam Dinh", "UPCOM"),
    ("NDP", "Công ty cổ phần Dược phẩm 2-9", "UPCOM"),
    ("NDT", "Tổng Công ty Cổ phần Dệt may Nam Định", "UPCOM"),
    ("NDW", "CTCP Cap nuoc Nam Dinh", "UPCOM"),
    ("NED", "CTCP Dau tu va Phat trien Dien Tay Bac", "UPCOM"),
    ("NGC", "Công ty Cổ phần Chế biến Thủy sản xuất khẩu Ngô Quyền", "UPCOM"),
    ("NHD", "Cổ phiếu CTCP Dược phẩm Nam Hà", "UPCOM"),
    ("NHV", "Công ty cổ phần Sức khỏe Hồi sinh Việt Nam", "UPCOM"),
    ("NJC", "CTCP May Nam Định", "UPCOM"),
    ("NLS", "CTCP Cap thoat nuoc Lang Son", "UPCOM"),
    ("NNT", "Cổ phiếu CTCP Cấp nước Ninh Thuận", "UPCOM"),
    ("NOS", "Công ty cổ phần Vận tải Biển và Thương mại Phương Đông", "UPCOM"),
    ("NQB", "CTCP Cap nuoc Quang Binh", "UPCOM"),
    ("NQN", "CTCP Nuoc sach Quang ninh", "UPCOM"),
    ("NSG", "CTCP Nhua Sai Gon", "UPCOM"),
    ("NSL", "CTCP cap nuoc Son La", "UPCOM"),
    ("NSS", "CTCP Nông Súc Sản Đồng Nai", "UPCOM"),
    ("NTF", "CTCP Duoc - Vat tu Y te Nghe An", "UPCOM"),
    ("NTT", "CTCP Det - May Nha Trang", "UPCOM"),
    ("NTW", "Cổ phiếu Công ty cổ phần Cấp nước Nhơn Trạch", "UPCOM"),
    ("NUE", "CTCP Moi truong Do thi Nha Trang", "UPCOM"),
    ("NVP", "CTCP Nuoc sach Vinh Phuc", "UPCOM"),
    ("NWT", "CTCP Van tai Newway", "UPCOM"),
    ("NXT", "CTCP San xuat va Cung ung vat lieu xay dung Kon Tum", "UPCOM"),
    ("ODE", "Công ty cổ phần Tập đoàn Truyền thông và Giải trí ODE", "UPCOM"),
    ("OIL", "Tổng Công ty Dầu Việt Nam - Công ty cổ phần", "UPCOM"),
    ("ONW", "Công ty cổ phần Tập đoàn ONW", "UPCOM"),
    ("PAI", "CTCP Cong nghe thong tin, Vien thong va Tu dong hoa dau khi", "UPCOM"),
    ("PAP", "CTCP Dầu khí Đầu tư Khai thác Cảng Phước An", "UPCOM"),
    ("PAS", "PAS - CTCP Quoc Te Phuong Anh", "UPCOM"),
    ("PAT", "CTCP Photpho Apatit Việt Nam", "UPCOM"),
    ("PBC", "CTCP Dược phẩm Trung ương I - Pharbaco", "UPCOM"),
    ("PBT", "Công ty Cổ phần Bao bì và Thương mại Dầu khí Bình Sơn", "UPCOM"),
    ("PCC", "Công ty cổ phần Tập đoàn Xây lắp 1- Petrolimex", "UPCOM"),
    ("PCF", "CTCP Ca phe Petec", "UPCOM"),
    ("PCG", "Cổ phiếu Công ty Cổ phần Đầu tư Phát triển Gas Đô thị", "UPCOM"),
    ("PCM", "CTCP vat lieu xay dung Buu dien", "UPCOM"),
    ("PDC", "Cổ phiếu CTCP Du lịch Dầu khí Phương Đông", "UPCOM"),
    ("PEG", "CTCP Tong cty Thuong mai ky thuat va Dau tu", "UPCOM"),
    ("PEQ", "CTCP Thiet bi Xang dau Petrolimex", "UPCOM"),
    ("PFL", "Công ty cổ phần Dầu khí Đông Đô", "UPCOM"),
    ("PGB", "Ngân hàng thương mại cổ phần Thịnh Vượng và Phát triển", "UPCOM"),
    ("PHH", "Công ty cổ phần Hồng Hà Việt Nam", "UPCOM"),
    ("PHP", "PHP - Cang Hai Phong", "UPCOM"),
    ("PHS", "PHS - CTCP Chứng khoán Phú Hưng", "UPCOM"),
    ("PID", "CTCP Trang Tri Noi That Dau Khi", "UPCOM"),
    ("PIS", "Tổng Công ty Pisico Bình Định - Công ty cổ phần", "UPCOM"),
    ("PIV", "Công ty cổ phần PIV", "UPCOM"),
    ("PJS", "PJS - Công ty Cổ phần Cấp nước Phú Hòa Tân", "UPCOM"),
    ("PLA", "CTCP Dau tu Dich vu ha tang Xang dau", "UPCOM"),
    ("PLE", "CTCP Tư vấn Xây dựng Petrolimex", "UPCOM"),
    ("PLO", "CTCP Kho van Petec", "UPCOM"),
    ("PMJ", "CTCP Vat tu Buu dien", "UPCOM"),
    ("PMT", "Công ty cổ phần Viễn thông Telvina Việt Nam", "UPCOM"),
    ("PMW", "CTCP Cấp nước Phú Mỹ", "UPCOM"),
    ("PND", "CTCP Xang dau Dau khi NamDinh", "UPCOM"),
    ("PNG", "CTCP Thuong Mai Phu Nhuan", "UPCOM"),
    ("PNP", "CTCP Tân Cảng - Phú Hữu", "UPCOM"),
    ("PNT", "CTCP Ky thuat Xay dung Phu Nhuan", "UPCOM"),
    ("POB", "CTCP Xang dau dau khi Thai Binh", "UPCOM"),
    ("POM", "CTCP thep Pomina", "UPCOM"),
    ("POS", "CTCP dich vu lap dat, van hanh va bao duong cong trinh dau khi bien PTSC", "UPCOM"),
    ("POV", "POV - Cổ phiếu CTCP Xăng dầu Dầu khí Vũng Áng", "UPCOM"),
    ("PPH", "Tong CTCP Phong Phu", "UPCOM"),
    ("PPI", "CTCP Dau tu va Phat trien Du an Ha tang Thai Binh Duong", "UPCOM"),
    ("PQN", "CTCP Dich vu Dau khi Quang Ngai PTSC", "UPCOM"),
    ("PRO", "CTCP Procimex Việt Nam", "UPCOM"),
    ("PRT", "CTCP Tong cty San xuat - Xuat nhap khau Binh Duong", "UPCOM"),
    ("PSB", "cổ phiếu CTCP Đầu tư Dầu khí Sao Mai - Bến Đình", "UPCOM"),
    ("PSH", "Cổ phiếu Công ty cổ phần Thương mại Đầu tư Dầu khí Nam Sông Hậu", "UPCOM"),
    ("PSL", "Cổ phiếu CTCP Chăn nuôi Phú Sơn", "UPCOM"),
    ("PSN", "CTCP Dịch vụ Kỹ thuật Tổng hợp PTSC Thanh Hóa", "UPCOM"),
    ("PSP", "cổ phiếu CTCP Cảng dịch vụ Dầu khí Đình Vũ", "UPCOM"),
    ("PTE", "PTE - CTCP Xi mang Phu Tho", "UPCOM"),
    ("PTG", "Cổ phiếu CTCP May xuất khẩu Phan Thiết", "UPCOM"),
    ("PTH", "Cổ phiếu CTCP Vận tải và Dịch vụ Petrolimex Hà Tây", "UPCOM"),
    ("PTM", "Cổ phiếu Công ty cổ phần Sản xuất, Thương mại và Dịch vụ Ô tô PTM", "UPCOM"),
    ("PTO", "CTCP Dich vu - Xay dung Cong trinh Buu dien", "UPCOM"),
    ("PTP", "Công ty cổ phần PTP", "UPCOM"),
    ("PTT", "Cổ phiếu CTCP Vận tải Dầu khí Đông Dương", "UPCOM"),
    ("PTV", "Công ty cổ phần Thương mại Dầu khí", "UPCOM"),
    ("PVE", "Tổng Công ty Tư vấn Thiết kế Dầu khí - CTCP", "UPCOM"),
    ("PVH", "CTCP Xay lap Dau khi Thanh Hoa", "UPCOM"),
    ("PVL", "Công ty cổ phần Đầu tư Nhà đất Việt", "UPCOM"),
    ("PVM", "CTCP May - Thiet bi Dau khi", "UPCOM"),
    ("PVO", "CTCP Dau Nhon PV OIL", "UPCOM"),
    ("PVR", "Công ty cổ phần Đầu tư PVR Hà Nội", "UPCOM"),
    ("PVV", "CTCP Vinaconex 39", "UPCOM"),
    ("PVX", "Cổ phiếu TCTCP Xây lắp Dầu khí Việt Nam", "UPCOM"),
    ("PVY", "Công ty Cổ phần Chế tạo Giàn khoan Dầu khí", "UPCOM"),
    ("PWA", "CTCP Bat dong san Dau khi", "UPCOM"),
    ("PWS", "CTCP Cap thoat nuoc Phu Yen", "UPCOM"),
    ("PXA", "Cổ phiếu CTCP Đầu tư và Thương mại Dầu khí Nghệ An", "UPCOM"),
    ("PXI", "CTCP Xay dung Cong nghiep va Dan dung dau khi", "UPCOM"),
    ("PXL", "Công ty cổ phần Đầu tư Khu Công nghiệp Dầu khí Long Sơn", "UPCOM"),
    ("PXM", "Công ty cổ phần Xây lắp Dầu khí Miền Trung", "UPCOM"),
    ("PXS", "CTCP Ket cau Kim loai va lap may dau khi", "UPCOM"),
    ("PXT", "Công ty cổ phần Xây lắp đường ống bể chứa Dầu khí", "UPCOM"),
    ("QBS", "CTCP Xuat nhap khau Quang Binh", "UPCOM"),
    ("QCC", "Công ty cổ phần Đầu tư Xây dựng và Phát triển Hạ tầng Viễn Thông", "UPCOM"),
    ("QHW", "CTCP nuoc khoang Quang Ninh", "UPCOM"),
    ("QNC", "Cổ phiếu CTCP Xi măng và Xây dựng Quảng Ninh", "UPCOM"),
    ("QNS", "CTCP DUONG QUANG NGAI", "UPCOM"),
    ("QNT", "Công ty cổ phần Tư vấn và Đầu tư phát triển Quảng Nam", "UPCOM"),
    ("QNU", "QNU- CTCP Moi truong do thi Quang Nam", "UPCOM"),
    ("QNW", "CTCP Cap thoat nuoc va xay dung Quang Ngai", "UPCOM"),
    ("QPH", "Công ty Cổ phần Thủy điện Quế Phong", "UPCOM"),
    ("QSP", "CTCP Tan Cang Quy Nhon", "UPCOM"),
    ("QTP", "CTCP Nhiet dien Quang Ninh", "UPCOM"),
    ("RAT", "CTCP Van tai va thuong mai Duong sat", "UPCOM"),
    ("RBC", "CTCP Công nghiệp và Xuất nhập khẩu Cao Su", "UPCOM"),
    ("RCC", "CTCP Tong cong ty Cong trinh duong sat", "UPCOM"),
    ("RCD", "CTCP Xây dựng - Địa ốc Cao su", "UPCOM"),
    ("RGG", "Cổ phiếu Công ty cổ phần Regal Group", "UPCOM"),
    ("RIC", "CTCP Quoc te Hoang gia", "UPCOM"),
    ("RTB", "CTCP Cao Su Tan Bien", "UPCOM"),
    ("SAC", "CTCP Xep do va Dich vu Cang Sai Gon", "UPCOM"),
    ("SAL", "CTCP truc vot cuu ho Viet Nam", "UPCOM"),
    ("SAS", "Công ty cổ phần Dịch vụ Hàng không Sân bay Tân Sơn Nhất", "UPCOM"),
    ("SBB", "CTCP Tap doan Bia Sai Gon Binh Tay", "UPCOM"),
    ("SBD", "CTCP Cong nghe Sao Bac Dau", "UPCOM"),
    ("SBH", "Công ty Cổ phần Thủy điện Sông Ba Hạ", "UPCOM"),
    ("SBL", "CTCP Bia Sai Gon - Bac Lieu", "UPCOM"),
    ("SBM", "CTCP Dau tu Phat trien Bac Minh", "UPCOM"),
    ("SBR", "CTCP Cao Su Song Be", "UPCOM"),
    ("SBS", "Công ty cổ phần Chứng khoán SBS", "UPCOM"),
    ("SCC", "Công ty cổ phần Thương mại Đầu tư SHB", "UPCOM"),
    ("SCD", "CTCP Nuoc giai khat Chuong Duong", "UPCOM"),
    ("SCJ", "CTCP Xi mang Sai Son", "UPCOM"),
    ("SCL", "SCL - CTCP Sông Đà Cao Cường", "UPCOM"),
    ("SCO", "Cổ phiếu CTCP Công nghiệp Thủy Sản", "UPCOM"),
    ("SDA", "Cổ phiếu Công ty cổ phần SIMCO Sông Đà", "UPCOM"),
    ("SDD", "Cổ phiếu CTCP Đầu tư và Xây lắp Sông Đà", "UPCOM"),
    ("SDK", "SDK - CTCP Cơ khí Luyện Kim", "UPCOM"),
    ("SDP", "CTCP SDP", "UPCOM"),
    ("SDT", "Cổ phiếu Công ty Cổ phần Sông Đà 10", "UPCOM"),
    ("SDV", "SDV - Công ty Cổ phần Dịch vụ Sonadezi", "UPCOM"),
    ("SDY", "Cổ phiếu CTCP Xi măng Sông Đà Yaly", "UPCOM"),
    ("SEA", "Tong Cong ty Thuy san Viet Nam - CTCP", "UPCOM"),
    ("SEP", "CTCP TCT Thuong mai Quang tri", "UPCOM"),
    ("SGB", "NHTM CP Sai Gon Cong Thuong", "UPCOM"),
    ("SGI", "CTCP Đầu tư phát triển Sài Gòn 3 Group", "UPCOM"),
    ("SGP", "CTCP Cang Sai Gon", "UPCOM"),
    ("SGS", "SGS - Công ty Cổ phần Vận tải Biển Sài Gòn", "UPCOM"),
    ("SHC", "Công Ty Cổ Phần Hàng Hải Sài Gòn", "UPCOM"),
    ("SID", "CTCP Dau tu va Phat trien Sai Gon Co.op", "UPCOM"),
    ("SIG", "CTCP Dau tu va Thuong mai Song Da", "UPCOM"),
    ("SII", "CTCP ha tang nuoc Sai Gon", "UPCOM"),
    ("SIV", "CTCP SIVICO", "UPCOM"),
    ("SJF", "CTCP Dau tu Sao Thai Duong", "UPCOM"),
    ("SJG", "CTCP Tong cong ty Song Da", "UPCOM"),
    ("SJM", "Cổ phiếu CTCP Sông Đà 19", "UPCOM"),
    ("SKH", "Công ty Cổ phần Nước giải khát Sanest Khánh Hòa", "UPCOM"),
    ("SKN", "CTCP nuoc giai khat Sanna Khanh Hoa", "UPCOM"),
    ("SKV", "CTCP nuoc giai khat Yen sao Khanh Hoa", "UPCOM"),
    ("SLD", "Cổ phiếu Công ty cổ phần Địa ốc Sacom", "UPCOM"),
    ("SNC", "CTCP Xuất nhập khẩu Thuỷ sản Năm Căn", "UPCOM"),
    ("SNZ", "Tổng Công ty Cổ phần Phát triển Khu công nghiệp", "UPCOM"),
    ("SPB", "CTCP Soi Phu Bai", "UPCOM"),
    ("SPD", "Cổ phiếu CTCP XNK Thuỷ sản Miền Trung", "UPCOM"),
    ("SPH", "CTCP Xuất nhập khẩu thủy sản Hà Nội", "UPCOM"),
    ("SPI", "Cổ phiếu Công ty cổ phần Spiral Galaxy", "UPCOM"),
    ("SPV", "CTCP Thuy Dac San", "UPCOM"),
    ("SRB", "Công ty Cổ phần Tập đoàn Sara", "UPCOM"),
    ("SSG", "Cổ phiếu CTCP Vận tải Biển Hải Âu", "UPCOM"),
    ("SSH", "CTCP Phát triển Sunshine Homes", "UPCOM"),
    ("STD", "CTCP Bia - Nước giải khát Sài Gòn - Tây Đô", "UPCOM"),
    ("STH", "CTCP Phát hành sách Thái Nguyên", "UPCOM"),
    ("STS", "Cổ phiếu CTCP Dịch vụ Vận tải Sài Gòn", "UPCOM"),
    ("STT", "CTCP Van chuyen Sai Gon Tourist", "UPCOM"),
    ("STW", "CTCP Cap nuoc Soc Trang", "UPCOM"),
    ("SVG", "CTCP Hoi Ky nghe Que han", "UPCOM"),
    ("SVH", "CTCP Thủy điện Sông Vàng", "UPCOM"),
    ("SWC", "Cổ phiếu Tổng CTCP Đường Sông Miền nam", "UPCOM"),
    ("SZE", "CTCP Moi truong Sonadezi", "UPCOM"),
    ("SZG", "CTCP Sonadezi Giang Dien", "UPCOM"),
    ("TAB", "Cong ty co phan Freco Viet Nam", "UPCOM"),
    ("TAN", "CTCP Ca Phe Thuan An", "UPCOM"),
    ("TAR", "CTCP Nông nghiệp CNC Trung An", "UPCOM"),
    ("TAW", "CTCP Cap nuoc Trung An", "UPCOM"),
    ("TBD", "Tổng Công ty Thiết bị Điện Đông Anh - CTCP", "UPCOM"),
    ("TBR", "CTCP Địa ốc Tân Bình", "UPCOM"),
    ("TBW", "Co Phieu CTCP Nuoc Sach Thai Binh", "UPCOM"),
    ("TCJ", "CTCP To Chau", "UPCOM"),
    ("TCK", "CTCP Tong cong ty co khi xay dung", "UPCOM"),
    ("TCW", "CTCP Kho vận Tân Cảng", "UPCOM"),
    ("TDB", "CTCP Thuy dien Binh Dinh", "UPCOM"),
    ("TDF", "CTCP Trung Đô", "UPCOM"),
    ("TDS", "Công ty cổ phần Thép Thủ Đức- VNSTEEL", "UPCOM"),
    ("TED", "CTCP Tong cty Tu van thiet ke Giao thong van tai", "UPCOM"),
    ("TGG", "CTCP The Golden Group", "UPCOM"),
    ("TGP", "Cổ phiếu Công ty cổ phần Trường Phú", "UPCOM"),
    ("THM", "CTCP Tứ Hải Hà Nam", "UPCOM"),
    ("THN", "CTCP Cap nuoc Thanh Hoa", "UPCOM"),
    ("THP", "CTCP Thuy san Va Thuong mai Thuan Phuoc", "UPCOM"),
    ("THU", "CTCP Moi truong va Cong trinh Do thi Thanh Hoa`", "UPCOM"),
    ("THW", "CTCP Cap nuoc Tan Hoa", "UPCOM"),
    ("TID", "CTCP Tong cty Tin Nghia", "UPCOM"),
    ("TIE", "CTCP TIE", "UPCOM"),
    ("TIN", "CTCP Tai chinh Co phan Tin Viet", "UPCOM"),
    ("TIS", "Cổ phiếu Công ty cổ phần Gang Thép Thái Nguyên", "UPCOM"),
    ("TKA", "CTCP Bao bi Tan Khanh An", "UPCOM"),
    ("TLP", "Tổng công ty Thương mại Xuất nhập khẩu Thanh Lễ - Công ty cổ phần", "UPCOM"),
    ("TMG", "CTCP Kim loai mau Thai Nguyen - Vimico", "UPCOM"),
    ("TMW", "CTCP Tổng hợp Gỗ tân Mai", "UPCOM"),
    ("TNA", "CTCP Thuong mai Xuat nhap khau Thien Nam", "UPCOM"),
    ("TNB", "Công ty cổ phần Thép Nhà Bè- VNSTEEL", "UPCOM"),
    ("TNP", "CTCP Cang Thi Nai", "UPCOM"),
    ("TNS", "CTCP Thep Tam la Thong nhat", "UPCOM"),
    ("TNW", "CTCP Nuoc sach Thai Nguyen", "UPCOM"),
    ("TOP", "CTCP Phan phoi Top one", "UPCOM"),
    ("TOS", "CTCP Dich vu bien Tan Cang", "UPCOM"),
    ("TOW", "CTCP Cap nuoc Tra Noc - O Mon", "UPCOM"),
    ("TPS", "CTCP Ben bai Van tai Sai Gon", "UPCOM"),
    ("TQW", "CTCP Cấp thoát nước Tuyên Quang", "UPCOM"),
    ("TRS", "CTCP van tai va dich vu hang hai", "UPCOM"),
    ("TRT", "Công ty cổ phần RedstarCera", "UPCOM"),
    ("TRV", "Công ty cổ phần Vận tải Đường sắt", "UPCOM"),
    ("TSD", "CTCP Du lich Truong son COECCO", "UPCOM"),
    ("TSG", "CTCP Thông tin tín hiệu Đường sắt Sài Gòn", "UPCOM"),
    ("TSJ", "CTCP Du lich dich vu Ha noi", "UPCOM"),
    ("TST", "Cổ phiếu CTCP Dịch vụ Kỹ thuật Viễn thông", "UPCOM"),
    ("TTB", "Công ty cổ phần TTBGROUP", "UPCOM"),
    ("TTD", "CTCP Benh vien Tim Tam Duc", "UPCOM"),
    ("TTG", "Cổ phiếu CTCP Royal Healthtech TTG", "UPCOM"),
    ("TTN", "Công ty cổ phần Công nghệ và Truyền thông Việt Nam", "UPCOM"),
    ("TTS", "CTCP Cán thép Thái Trung", "UPCOM"),
    ("TTZ", "CTCP Dau tu Xay dung va Cong nghe Tien Trung", "UPCOM"),
    ("TUG", "CTCP Lai dat va Van tai Cang Hai phong", "UPCOM"),
    ("TVA", "CTCP Su Viglacera Thanh Tri", "UPCOM"),
    ("TVG", "Cổ phiếu CTCP Tư vấn Đầu tư và Xây dựng Giao thông vận tải", "UPCOM"),
    ("TVH", "CTCP Tu van Xay dung Cong trinh Hang hai", "UPCOM"),
    ("TVM", "CTCP Tư vấn đầu tư mỏ và công nghiệp - Vinacomin", "UPCOM"),
    ("TVN", "CTCP - Tong cong ty Thep Viet Nam", "UPCOM"),
    ("UCT", "CTCP Do thi Can Tho", "UPCOM"),
    ("UDC", "CTCP Xay dung va Phat trien Do thi Tinh Ba Ria - Vung Tau", "UPCOM"),
    ("UDJ", "Cổ phiếu CTCP Phát triển Đô thị", "UPCOM"),
    ("UDL", "CTCP Đô thị và Môi trường Đắk Lắk", "UPCOM"),
    ("UEM", "CTCP Co dien Uong Bi - Vinacomin", "UPCOM"),
    ("UMC", "CTCP Cong trinh do thi Nam Dinh", "UPCOM"),
    ("UPC", "CTCP Phat trien Cong vien Cay xanh va Do thi Vung Tau", "UPCOM"),
    ("UPH", "CTCP Duoc pham TW25", "UPCOM"),
    ("UPS", "Cổ phiếu Công ty cổ phần Chứng khoán UP", "UPCOM"),
    ("USC", "CTCP Khao sat va Xay dung - USCO", "UPCOM"),
    ("USD", "CTCP Cong Trinh Do thi Soc Trang", "UPCOM"),
    ("UTT", "Công ty Cổ phần Môi trường Nam Thành", "UPCOM"),
    ("UXC", "CTCP Chế biến thủy sản Út Xi", "UPCOM"),
    ("VAF", "Cổ phiếu Công ty cổ phần Phân lân nung chảy Văn Điển", "UPCOM"),
    ("VAV", "CTCP VIWACO", "UPCOM"),
    ("VBG", "CTCP Dia chat Viet Bac - TKV", "UPCOM"),
    ("VBH", "Cổ phiếu CTCP Điện tử Bình Hoà", "UPCOM"),
    ("VBT", "Cổ phiếu Công ty cổ phần Vận tải Bảo Thắng", "UPCOM"),
    ("VCE", "CTCP Xay lap Moi truong - TKV", "UPCOM"),
    ("VCP", "Công ty cổ phần Xây dựng và Năng lượng VCP", "UPCOM"),
    ("VCR", "CÔNG TY CỔ PHẦN ĐẦU TƯ VÀ PHÁT TRIỂN DU LỊCH ITC", "UPCOM"),
    ("VCT", "VCT - CTCP Tư vấn Xây dựng Vinaconex", "UPCOM"),
    ("VCX", "CTCP Xi Măng Yên Bình", "UPCOM"),
    ("VDB", "CTCP Van tai va Che bien Than Dong Bac", "UPCOM"),
    ("VDG", "CTCP Vạn Đạt Group", "UPCOM"),
    ("VDN", "Cổ phiếu CTCP Vinatex Đà Nẵng", "UPCOM"),
    ("VDT", "VDT - Công ty Cổ phần Lưới thép Bình Tây", "UPCOM"),
    ("VEA", "CTCP Tong cty May dong luc va May nong nghiep Viet Nam", "UPCOM"),
    ("VEC", "Tong CTCP Dien tu va Tin hoc Viet Nam", "UPCOM"),
    ("VEF", "CTCP Trung tâm Hội chợ Triển lãm Việt Nam", "UPCOM"),
    ("VES", "CÔNG TY CỔ PHẦN TẬP ĐOÀN VINALIVING", "UPCOM"),
    ("VET", "CTCP Thuoc thu y Trung uong Navetco", "UPCOM"),
    ("VFC", "Cổ Phiếu CTCP VINAFCO", "UPCOM"),
    ("VFR", "Cổ phiếu Công ty Cổ phần Vận tải và Thuê tàu", "UPCOM"),
    ("VGG", "CTCP May Viet Tien", "UPCOM"),
    ("VGI", "CTCP Dau tu quoc te Viettel", "UPCOM"),
    ("VGL", "CTCP Ma kem cong nghiep Vingal-Vnsteel", "UPCOM"),
    ("VGR", "CTCP Cang Xanh VIP", "UPCOM"),
    ("VGT", "CTCP - Tap doan Det may Viet Nam", "UPCOM"),
    ("VGV", "Tong Cong ty Tu van Xay dung Viet nam", "UPCOM"),
    ("VHD", "Công ty cổ phần Đầu tư Phát triển nhà và Đô thị VINAHUD", "UPCOM"),
    ("VHF", "Cổ phiếu CTCP Xây dựng và Chế biến lương thực Vĩnh Hà", "UPCOM"),
    ("VHG", "Công ty cổ phần Đầu tư và Phát triển Việt Trung Nam", "UPCOM"),
    ("VHH", "Công ty cổ phần Đầu tư Kinh doanh nhà Thành Đạt", "UPCOM"),
    ("VIE", "Cổ phiếu CTCP Công nghệ Viễn thông VI TE CO", "UPCOM"),
    ("VIM", "CTCP Khoang san Viglacera", "UPCOM"),
    ("VIN", "CTCP Giao nhận Kho vận Ngoại thương Việt Nam", "UPCOM"),
    ("VIR", "Cổ phiếu CTCP Du lịch Quốc tế Vũng Tàu", "UPCOM"),
    ("VIW", "CTCP Tong cty Dau tu Nuoc & Moi truong Viet Nam", "UPCOM"),
    ("VKC", "Công ty cổ phần VKC Holdings", "UPCOM"),
    ("VLB", "CTCP Xay dung va San xuat vat lieu xay dung Bien Hoa", "UPCOM"),
    ("VLC", "Tong Cong ty Chan nuoi Viet Nam - CTCP", "UPCOM"),
    ("VLG", "Công ty cổ phần VIMC Logistics", "UPCOM"),
    ("VLP", "CTCP Cong trinh Cong cong Vinh Long", "UPCOM"),
    ("VLS", "Cổ phiếu Công ty cổ phần Sản xuất Thép Việt Long", "UPCOM"),
    ("VLW", "CTCP Cap nuoc Vinh Long", "UPCOM"),
    ("VMA", "CTCP Cong nghiep Oto - Vinacomin", "UPCOM"),
    ("VMG", "CTCP Thương mại và dịch vụ Dầu khí Vũng Tàu", "UPCOM"),
    ("VMK", "CTCP Vimarko", "UPCOM"),
    ("VMT", "CTCP GIAO NHAN VAN TAI MIEN TRUNG", "UPCOM"),
    ("VNA", "CTCP Van tai bien Vinaship", "UPCOM"),
    ("VNB", "CTCP Sach Viet Nam", "UPCOM"),
    ("VNE", "Cổ phiếu Tổng Công ty cổ phần Xây dựng điện Việt Nam", "UPCOM"),
    ("VNH", "Công ty cổ phần Đầu tư Việt Việt Nhật", "UPCOM"),
    ("VNI", "VNI - CTCP Dau Tu Bat Dong San Viet Nam", "UPCOM"),
    ("VNP", "CTCP Nhựa Việt Nam", "UPCOM"),
    ("VNX", "Công ty cổ phần Quảng cáo và Hội chợ Thương Mại Vinexad", "UPCOM"),
    ("VNY", "CTCP Thuốc thú y TƯ I", "UPCOM"),
    ("VNZ", "CONG TY CP VNG", "UPCOM"),
    ("VPA", "CTCP Van tai Hoa dau VP", "UPCOM"),
    ("VPC", "Cổ phiếu Công ty cổ phần  Đầu tư và Phát triển Năng lượng Việt Nam", "UPCOM"),
    ("VPR", "Công ty cổ phần Vinaprint", "UPCOM"),
    ("VPW", "CTCP Cấp thoát nước số 1 Vĩnh Phúc", "UPCOM"),
    ("VQC", "Công ty cổ phần Giám định- Vinacomin", "UPCOM"),
    ("VRG", "VRG - CTCP Phat trien do thi va Khu cong nghiep Cao Su Viet Nam", "UPCOM"),
    ("VSE", "CTCP Dich vu Duong cao toc Viet Nam", "UPCOM"),
    ("VSF", "CTCP Tong cong ty Luong thuc Mien Nam", "UPCOM"),
    ("VSG", "Cổ phiếu CTCP CONTAINER Phía Nam", "UPCOM"),
    ("VSN", "CTCP Viet Nam Ky nghe Suc san", "UPCOM"),
    ("VST", "CTCP Vận tải và Thuê tàu biển Việt Nam", "UPCOM"),
    ("VTA", "Cổ phiếu CTCP Vitaly", "UPCOM"),
    ("VTD", "Công ty cổ phần Vietourist Holdings", "UPCOM"),
    ("VTE", "Công ty cổ phần Vinacap Kim Long", "UPCOM"),
    ("VTG", "CTCP Du lich tinh Ba ria - Vung tau", "UPCOM"),
    ("VTI", "Cổ phiếu CTCP Sản xuất - Xuất nhập khẩu dệt may", "UPCOM"),
    ("VTK", "Công ty cổ phần Tư vấn và Dịch vụ Viettel", "UPCOM"),
    ("VTM", "CTCP Van tai va Dua don tho mo - Vinacomin", "UPCOM"),
    ("VTQ", "Công ty cổ phần Việt Trung Quảng Bình", "UPCOM"),
    ("VTR", "Công ty Cổ phần Du lịch Vietravel", "UPCOM"),
    ("VTS", "Công ty cổ phần Gạch ngói Từ Sơn", "UPCOM"),
    ("VTX", "Công ty cổ phần Vận tải đa phương thức VIETRANSTIMEX", "UPCOM"),
    ("VUA", "CTCP Chung khoan Stanley Brothers", "UPCOM"),
    ("VVN", "Tổng CTCP Xây dựng công nghiệp VN", "UPCOM"),
    ("VWS", "CTCP Nuoc va Moi truong Viet Nam", "UPCOM"),
    ("VXB", "Cổ phiếu CTCP Vật liệu Xây dựng Bến Tre", "UPCOM"),
    ("VXP", "CTCP Thuoc Thu y Trung uong VETVACO", "UPCOM"),
    ("VXT", "CTCP Kho van va Dich vu Thuong mai", "UPCOM"),
    ("WSB", "Cổ phiếu Công ty cổ phần Bia Sài Gòn - Miền Tây", "UPCOM"),
    ("WTC", "Công ty cổ phần vận tải thủy Vinacomin", "UPCOM"),
    ("XDH", "CTCP Đầu tư Xây dựng Dân dụng Hà Nội", "UPCOM"),
    ("XHC", "Công ty CP Xuân Hòa Việt Nam", "UPCOM"),
    ("XLV", "CTCP xay lap va dich vu Song Da", "UPCOM"),
    ("XMC", "Công ty cổ phần Đầu tư và Xây dựng Xuân Mai", "UPCOM"),
    ("XMD", "CTCP Xuan Mai - Dao Tu", "UPCOM"),
    ("XMP", "CTCP Thủy điện Xuân Minh", "UPCOM"),
    ("XPH", "CTCP Xà phòng Hà Nội", "UPCOM"),
    ("YBC", "Cổ phiếu Công ty CP Xi măng và khoáng sản yên Bái", "UPCOM"),
    ("YTC", "CTCP Xuat nhap khau Y te Thanh pho Ho Chi Minh", "UPCOM"),
]
